==== Tangent Plane

[[req_sdu_tangentplane_longitude]]
[width="90%",cols="2,6"]
|===
^|*Requirement {counter:req-id}* |*/req/sdu/tangentplane/longitude* 
^|Requirement |The Logical Model attribute tangentPoint.longitude attribute shall denote an angle in degrees, represented as an IEEE 754 floating point value in a Structural Data Unit. The minimum value shall be -180.0 degrees and the maximum value shall be 180.0 degrees.
^|ID |<<req_sdu_tangentplane_longitude,/req/sdu/tangentplane/longitude>>
|===

[[req_sdu_tangentplane_latitude]]
[width="90%",cols="2,6"]
|===
^|*Requirement {counter:req-id}* |*/req/sdu/tangentplane/latitude* 
^|Requirement |The Logical Model attribute tangentPoint.latitude attribute shall denote an angle in degrees, represented as an IEEE 754 floating point value in a Structural Data Unit. The minimum value shall be 90.0 degrees and the maximum value shall be 90.0 degrees.
^|ID |<<req_sdu_tangentplane_latitude,/req/sdu/tangentplane/latitude>>
|===

[[req_sdu_tangentplane_height]]
[width="90%",cols="2,6"]
|===
^|*Requirement {counter:req-id}* |*/req/sdu/tangentplane/height* 
^|Requirement |The Logical Model attribute tangentPoint.height attribute shall denote a distance in meters, represented as an IEEE 754 floating point value in a Structural Data Unit.
^|ID |<<req_sdu_tangentplane_height,req/sdu/tangentplane/height>>
|===
