== Web Service for Solar GeoPose Examples and Validation

The service responds to HTTPS GET requests for examples of any of the JSON-encoded Standardization Targets, giving a single or sequence of GeoPoses for a specified latitude, longitude, and Unix time - default time "Now". It also responds to HTTPS POST requests to validate examples of any of the Standardization Targets. To see the OpenAPI/Swagger spec for the service, visit the link:https://geopose.io/swagger/index.html[SolarPose Swagger - OpenAPI]  UI.

The GeoPoses provided in the samples and in the validator are the pose of a camera or other body located at the anchor location of the GeoPose and oriented toward the current direction of the sun. Before applying the _yaw_, _pitch_, and _roll_ angle rotations the camera is aligned with the axes of the outer reference frame. The first angle (_yaw_) is the rotation about the z axis: the horizontal direction of the Sun. The second angle (_pitch_) is the rotation about the (once rotated) y axis: the elevation of the Sun above the horizon. If the second angle is positive, then it is daytime. Otherwise it is night. The third angle (_roll_) is the rotation about the (twice rotated) z axis. It is always zero because the camera is (arbitrarily) kept horizontal with respect to the tangent plane. The samples in sequences are at successive times: now, 10 seconds in the future, and 20 seconds in the future.

This service is used to validate the specifications and instances in the JSON encodings in the GeoPose standard.

The Solar Pose service is avaiable as a Web service. An http GET request using the URL template https://geopose.io/solarpose/<geopose type>?longitude=<longitude>&latitude=<latitude>&height=<height above ellipsoid>&unixTimeMs=<milliseconds since January 1st, 1970> will return a GeoPose of type <geopose type>. The GeoPose type choices are *quaternion*, *advanced*, and *ypr*. For example, https://geopose.io/solarpose/YPR?longitude=-105.24567&latitude=40.032074&height=0&unixTimeMs=1760209666368 (UCAR Center in Boulder, Colorado, USA at 16:30 UTC on 11 October 2025) returns 
```
{
  "position": {
    "lat": 40.032074,
    "lon": -105.24567,
    "h": 0
  },
  "angles": {
    "yaw": 186.85202367802975,
    "pitch": 42.95363113107107,
    "roll": 0
  }

```

A demo web app using the service is in the demo folder.
[link]
