
[appendix]
== Glossary

=== acceleration

time rate of change of {{velocity}}

=== accelerometer

sensor that can measure {{acceleration}}

NOTE: Low cost, accurate sensors for measuring 3 mutually perpendicular
components of acceleration are widely deployed in vehicles, communications
devices, and other connected devices.

=== angular acceleration

time rate of change of rotational {{velocity}}

=== application domain

context within which some technology or device is usefully applied

=== associated reference frame
admitted:[pose frame]

Euclidean {{reference frame}} that is defined by the location and orientation of a
{{pose}}

NOTE: A pose defines the origin of its associated reference frame, and its
{{orientation}} defines the orientation of its associated reference frame.

NOTE: Associated reference frames are useful in many simulation and graphics
applications where poses are most naturally defined in terms of another (parent)
object's pose.

=== attribute

{{property}} associated with an object

NOTE: In object modelling, an attribute is the same as a property or data member.

=== barometric pressure

ambient pressure of the atmosphere at a location

NOTE: Low cost, accurate sensors for barometric pressure are widely deployed in
connected devices.

NOTE: Sensing of changes in barometric pressure over time periods of minutes or
less is enables estimation of vertical relative position.

=== Bluetooth indoor positioning service

indoor positioning service based on Bluetooth signal strength and/or triangulation

NOTE: A Bluetooth indoor positioning service allows precise determination of
location and orientation inside smaller spaces.

NOTE: The location of a Bluetooth transceiver may be specified with respect to a
geographic coordinate system and it may be possible to compute a GeoPose from
interactions with multiple Bluetooth transceivers or other sensors.

=== 3-D cartesian coordinate system
admitted:[cartesian coordinate system]

system of geometrical reference using three mutually perpendicular axes where a
point location is described by three numbers giving the perpendicular distance
to each of the axes, all in the same numerical scale

=== class

template for the data structure and methods for operating on those data
structures for objects sharing common characteristics

=== compass

sensor for measuring the relative orientation of a device to an ambient magnetic
field

NOTE: Accurate and low-cost compasses are widely deployed in connected devices.

=== coordinate reference system

coordinate system referenced to a {{datum}}

=== data type

representational form for a concrete data element such as a number, character,
or colour

=== datum

reference point, line or surface used to establish measurements of position

NOTE: A datum is typically specified as a set of parameters that define the
position of the origin, the scale, and the orientation of a coordinate system.

=== geodetic datum

{{datum}} that defines the measurement of horizontal position (latitude and
longitude) and/or vertical position (height)

=== ellipsoid

mathematical surface that may be used as a {{datum}} in defining a {{geographic
coordinate system}}

NOTE: An ellipsoid is usually established by fitting the parameters of the
ellipsoid to measurements of a gravitational equipotential surface ({{geoid}})
that approximates mean sea level.

=== east-north-up local tangent plane coordinate system
admitted:[ENU coordinate system]

Euclidean 3-D coordinate system aligned with the Z-axis increasing
upward, the X-axis aligned toward the direction east, and the Y-axis aligned
toward north

NOTE: An ENU coordinate system is not defined at the poles because there is no
inherent orientation.

=== Euler angles

description of the orientation of one Euclidean {{reference frame}} to another by
specifying the rotations about each of the three axes respectively to bring one
in alignment with the other

=== geographic coordinates

3-dimensional reference system based on a reference {{ellipsoid}}

NOTE: Two of the coordinates are angles with respect to the axis of the
ellipsoid and to a plane containing the axis of the ellipsoid and a specified
point (principle point) on the ellipsoid surface. The third coordinate is a
linear measure of height above the ellipsoidal surface.

=== geographic position

point defined in geographic coordinates

=== geoid

approximation of surface of equal gravitational force, usually attempting to
match average sea-level

NOTE: A geoid is defined by measurements and is always inexact. The {{ellipsoid}}
used in {{geographic coordinates,geographic coordinate systems}} is
usually a mathematical approximation to a specific geoid.

=== gyro

sensor that measures the rate of rotation

NOTE: Low-cost, accurate Gyros are widely deployed in connected devices.

=== kinematics

properties of location, velocity, and acceleration of a body without regard to
any forces acting on the body

=== local tangent plane coordinate system
admitted:[LTP coordinate system]

right-hand Euclidean coordinate system with a vertical (Z) axis extending
from an origin at a point defined by geographic coordinates with respect to an
{{ellipsoid}}

=== local tangent plane east-north-up coordinate system
admitted:[local tangent plane east-north-up frame]
admitted:[LTP-ENU coordinate system]

{{local tangent plane coordinate system}} specialized to an east-north-up system,
where the X axis is aligned toward east and the Y axis toward north.

NOTE: While a {{LTP coordinate system}} can be established at any location, an
ENU cannot be defined at the poles because it cannot be oriented.

=== position

location of a point with respect to the origin of a specific {{reference frame}}

=== property

{{attribute}} associated with an object

NOTE: In object modelling, it is the same as an {{attribute}} or data member.

=== quaternions

extension of complex numbers

NOTE: Quaternions provide convenient properties for computing with rotations, in
particular smooth interpolation and avoidance of "gimbal lock" possible with
Euler Angles.

=== rotation

angular relationship between a reference frame's axes and a direction in that
{{reference frame}}

NOTE: {{Euler angles}}, rotation matrices, and {{quaternions}} are three ways to
specify a rotation.

=== digital sensor
admitted:[sensor]

device that converts environmental properties into data suitable for computation

=== topographic surface

interface between the liquid or solid surface of a planet and its atmosphere or
surrounding empty space

NOTE: The topographic surface is always approximate. It may be measured with
reference to a gravitational equipotential surface (such as a {{geoid}}) or a
mathematical reference surface (such as an {{ellipsoid}}).

=== velocity

time rate of change of {{position}}

=== vertical datum

reference level from which elevation or altitude can be measured

NOTE: The {{topographic surface}}, a {{geoid}}, a level of constant
{{barometric pressure}}, or an {{ellipsoid}} are examples.
