[appendix]
:appendix-caption: Annex
[[abstract-test-suite]]
== Abstract Test Suite (Normative)

=== Introduction

GeoPose 1.0 specifies a eight Standardization Targets using elements of the Logical Model. These elements are Structural Data Units (SDUs) and they have the stereotype "Structural Data Unit - SDU". Each SDU is an element of the Logical Model that will be expressed in concrete data objects encoded using specific encoding or serialization technologies. 

Although implementation of the Standardization Targets, expressed as SDUs, is independent of the Logical Model, GeoPose 1.0 also defines one of many possible implementations, single encoding in JavaScript Object Notation (JSON). The encodings of the eight targets are specified using JSON-Schema-2019-09. To keep the individual Standardization targets independent, there are some SDU requirements and corresponding conformance tests that appear in more than one requirement or conformance class. This structure is based on the judgement that it is easier to understand the independence of targets with complete definitions than would be the case if the definitional requirements of the SDUs were factored out and referenced indirectly by individual encodings.

=== Global Conformance Class

Conformance with the Global Requirements is required for all implementations.

[[conf_global]]
[width="100%",%header,cols="2,6"]
|===
<|*Conformance Class:* <|*Global* 

<s|ID |<<conf_global,/conf/global>>
<s|Target Type|SDU
<s|Description| Conformance with Global SDU requirements
<s|Dependency| None
<s|Test: G-Target|/conf/target_dependency
<s|Test: G-SDU|/conf/sdu_general 
<s|Test: G-LM|/conf/lm_general 

|===

The individual global tests are:

[[conformance_global]]
[width="100%",cols="2,6"]
|===
<s|Test:  s|G-Target

<s|ID |<<conf_global,/conf/target_dependency>>
2+<|There SHALL be no dependency between or among the individual Standardization Targets.
<s|Purpose|Verify that this requirement is satisfied
<s|Method|Inspection
<s|Reference: G-Target|/req/target_dependency
<s|Test Type|Conformance
|===


[[conformance_sdu]]
[width="100%",cols="2,6"]
|===
<s|Test:  s|G-SDU



<s|ID |<<conf_sdu_general,/conf/sdu_general>>
2+<|Implementations using encoded SDUs SHALL conform to the logical description of the Logical Model elements with the "Structural Data Unit - SDU" stereotype.
<s|Purpose|Verify that this requirement is satisfied
<s|Method|Inspection
<s|Reference: G-SDU|/req/sdu_general
<s|Test Type|Conformance
|===


[[conformance_lm]]
[width="100%",cols="2,6"]
|===
<s|Test:  s|G-LM

<s|ID |<<conf_lm_general,/conf/lm_general>>
2+<|Implementations of concrete data conforming to this standard SHALL conform to all dependent or inherited classes, attributes, and associations, multiplicities, and data types in the Logical Model.
<s|Purpose|Verify that this requirement is satisfied
<s|Method|Inspection
<s|Reference: G-LM|/req/lm_general
<s|Test Type|Conformance
|===


=== Structural Data Unit (SDU) Conformance

There are some universal requirements on values that appear in a concrete implementation using a specific encoding technology. For example, angles may be constrainted to fall within a range of values correponding to a circle. Because these are independent of encoding technology, they are specified here at a logical level. Tests of an implementation at the SDU level generally only be done by inspection.

=== Basic-YPR SDU Conformance Class

[[conf_basic_ypr]]
[width="100%",%header,cols="3,6"]
|===
<|*Conformance Class:* <|*Basic-YPR SDU* 

<s|ID |<<conf_basic_ypr_sdu,/conf/basic_ypr_sdu>>
<s|Target Type|SDU
<s|Description|To confirm that a Basic-YPR GeoPose consists of an Outer Frame specified by an implicit WGS-84 CRS and an implicit EPSG 4461-CS (LTP-ENU) coordinate system and explicit parameters defining the tangent point and that the Inner Frame is a rotation-only transformation using Yaw, Pitch, and Roll angles.
<s|Dependency| /conf/global
<s|Test: Basic-YPR|/conf/basic_ypr_sdu
<s|Test: Tangent-Plane Longitude|/conf/tangent_plane/longitude 
<s|Test: Tangent-Plane Latitude|/conf/tangent_plane/latitude 
<s|Test: Tangent-Plane h |/conf/tangent_plane/h 
|===

The Basic-YPR SDU member tests are the following:

[[conformance_global]]
[width="100%",cols="2,6"]
|===
<s|Test:  s|G-Target

<s|ID |<<at_global,/at/target_dependency>>
2+<|There SHALL be no dependency between or among the individual Standardization Targets.
<s|Purpose|Verify that this requirement is satisfied
<s|Method|Inspection
<s|Reference: G-Target|/req/target_dependency
<s|Test Type|Conformance
|===


[[ats_basic_ypr_sdu]]
[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/ats/basic/ypr/sdu* 
^|Test Purpose |To confirm that a Basic-YPR GeoPose consists of an Outer Frame specified by an implicit WGS-84 CRS and an implicit EPSG 4461-CS (LTP-ENU) coordinate system and explicit parameters defining the tangent point and that the Inner Frame is a rotation-only transformation using Yaw, Pitch, and Roll angles.
^|Requirement |/req_basic/ypr/sdu
^|Test Method |Inspection
|===

[[ats_tangent_plane_longitude_sdu]]
[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/ats/tangent_plane/longitude/sdu* 
^|Test Purpose |To confirm that a GeoPose tangentPoint.longitude attribute is expressed as a real number.
^|Requirement |/req/tangent_plane/longitude/sdu
^|Test Method |Inspection
|===

[[ats_tangent_plane_latitude_sdu]]
[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/ats/tangent_plane/latitude/sdu* 
^|Test Purpose |To confirm that a GeoPose tangentPoint.latitude attribute is expressed as a real number.
^|Requirement |/req/tangent_plane/latitude/sdu
^|Test Method |Inspection
|===

[[ats_tangent_plane_h_sdu]]
[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/ats/tangent_plane/h/sdu* 
^|Test Purpose |To confirm that a GeoPose tangentPoint.h attribute is expressed as a real number.
^|Requirement |/req/tangent_plane/h/sdu
^|Test Method |Inspection
|===

[[ats_orientation_ypr_angles_sdu]]
[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/ats/orientation/ypr/angles/sdu* 
^|Test Purpose |To confirm that GeoPose YPR angles are expressed as three consecutive rotations about the local axes Z, Y, and X, in that order, corresponding to the conventional Yaw, Pitch, and Roll angles and that the unit of measure is the degree..
^|Requirement |/ats/orientation/ypr/angles/sdu
^|Test Method |Inspection
|===

==== Basic-Q SDU Conformance Class

[[ats_basic_quaternion_sdu]]
[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/ats/basic/quaternion/sdu* 
^|Test Purpose |To confirm that a Basic-Q GeoPose consists of an Outer Frame specified by an implicit WGS-84 CRS and an implicit EPSG 4461-CS (LTP-ENU) coordinate system and explicit parameters defining the tangent point and that the Inner Frame is a rotation-only transformation using a unit quaternion.
^|Requirement |/req/basic/quaternion/sdu
^|Test Method |Inspection
|===

[[ats_tangent_plane_longitude_sdu]]
[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/ats/tangent_plane/longitude/sdu* 
^|Test Purpose |To confirm that a GeoPose tangentPoint.longitude attribute is expressed as a real number.
^|Requirement |/req/tangent_plane/longitude/sdu
^|Test Method |Inspection
|===

[[ats_tangent_plane_latitude_sdu]]
[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/ats/tangent_plane/latitude/sdu* 
^|Test Purpose |To confirm that a GeoPose tangentPoint.latitude attribute is expressed as a real number.
^|Requirement |/req/tangent_plane/latitude/sdu
^|Test Method |Inspection
|===

[[ats_tangent_plane_h_sdu]]
[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/ats/tangent_plane/h/sdu* 
^|Test Purpose |To confirm that a GeoPose tangentPoint.h attribute is expressed as a real number.
^|Requirement |/req/tangent_plane/h/sdu
^|Test Method |Inspection
|===

[[ats_orientation_quaternion_sdu]]
[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/ats/orientation/quaternion/sdu* 
^|Test Purpose |To confirm that GeoPose YPR angles are expressed as three consecutive rotations about the local axes Z, Y, and X, in that order, corresponding to the conventional Yaw, Pitch, and Roll angles and that the unit of measure is the degree..
^|Requirement |/req/orientation/quaternion/sdu
^|Test Method |Inspection
|===

==== Advanced SDU Conformance Class

[[req_advanced_sdu]]

[[ats_geoposeinstant_sdu]]
[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/ats/geoposeinstant/sdu* 
^|Test Purpose |To confirm that a Logical Model attribute GeoPoseInstant is Unix Time in seconds multiplied by 1,000 and that the unit of measure is milliseconds.
^|Requirement |/req/geoposeinstant/sdu
^|Test Method |Inspection
|===

[[ats_frame_specification_authority_sdu]]
[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/ats/frame_specification_authority/sdu* 
^|Test Purpose |To confirm that a FrameSpecification.authority attribute contains a string uniquely specifying a source of reference frame specifications.
^|Requirement |/req/frame_specification_authority/sdu
^|Test Method |Inspection
|===

[[ats_frame_specification_id_sdu]]
[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/ats/frame_specification_id/sdu* 
^|Test Purpose |To confirm that a FrameSpecification.id attribute is a string uniquely defining a frame within the authority.
^|Requirement |/req/frame_specification_id/sdu
^|Test Method |Inspection
|===

[[ats_frame_specification_parameters_sdu]]
[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/ats/frame_specification_parameters/sdu* 
^|Test Purpose |To confirm that a FrameSpecification.parameters attribute contains contain all parameters needed for the corresponding authority and ID.
^|Requirement |/req/frame_specification_parameters/sdu
^|Test Method |Inspection
|===


[[ats_orientation_quaternion_sdu]]
[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/ats/orientation/quaternion/sdu* 
^|Test Purpose |To confirm that GeoPose YPR angles are expressed as three consecutive rotations about the local axes Z, Y, and X, in that order, corresponding to the conventional Yaw, Pitch, and Roll angles and that the unit of measure is the degree..
^|Requirement |/req/orientation/quaternion/sdu
^|Test Method |Inspection
|===

==== Graph SDU Conformance Class


[[ats_geoposeinstant_sdu]]
[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/ats/geoposeinstant/sdu* 
^|Test Purpose |To confirm that a Logical Model attribute GeoPoseInstant is Unix Time in seconds multiplied by 1,000 and that the unit of measure is milliseconds.
^|Requirement |/req/geoposeinstant/sdu
^|Test Method |Inspection
|===


[[ats_frame_specification_authority_sdu]]
[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/ats/frame_specification_authority/sdu* 
^|Test Purpose |To confirm that a FrameSpecification.authority attribute contains a string uniquely specifying a source of reference frame specifications.
^|Requirement |/req/frame_specification_authority/sdu
^|Test Method |Inspection
|===

[[ats_frame_specification_id_sdu]]
[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/ats/frame_specification_id/sdu* 
^|Test Purpose |To confirm that a FrameSpecification.id attribute is a string uniquely defining a frame within the authority.
^|Requirement |/req/frame_specification_id/sdu
^|Test Method |Inspection
|===

[[ats_frame_specification_parameters_sdu]]
[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/ats/frame_specification_parameters/sdu* 
^|Test Purpose |To confirm that a FrameSpecification.parameters attribute contains contain all parameters needed for the corresponding authority and ID.
^|Requirement |/req/frame_specification_parameters/sdu
^|Test Method |Inspection
|===

[[ats_chain_index_sdu]]
[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/ats/chain/index/sdu* 
^|Test Purpose |To confirm that each index vaue in a FrameListTransformPair is a distinct integer value between 0 and one less than the number of elements in the frameList property.
^|Requirement |/req/Chain/index/sdu
^|Test Method |Inspection
|===


==== Chain SDU Conformance Class

[[ats_geoposeinstant_sdu]]
[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/ats/geoposeinstant/sdu* 
^|Test Purpose |To confirm that a Logical Model attribute GeoPoseInstant is Unix Time in seconds multiplied by 1,000 and that the unit of measure is milliseconds.
^|Requirement |/req/geoposeinstant/sdu
^|Test Method |Inspection
|===

[[ats_frame_specification_authority_sdu]]
[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/ats/frame_specification_authority/sdu* 
^|Test Purpose |To confirm that a FrameSpecification.authority attribute contains a string uniquely specifying a source of reference frame specifications.
^|Requirement |/req/frame_specification_authority/sdu
^|Test Method |Inspection
|===

[[ats_frame_specification_id_sdu]]
[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/ats/frame_specification_id/sdu* 
^|Test Purpose |To confirm that a FrameSpecification.id attribute is a string uniquely defining a frame within the authority.
^|Requirement |/req/frame_specification_id/sdu
^|Test Method |Inspection
|===

[[ats_frame_specification_parameters_sdu]]
[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/ats/frame_specification_parameters/sdu* 
^|Test Purpose |To confirm that a FrameSpecification.parameters attribute contains contain all parameters needed for the corresponding authority and ID.
^|Requirement |/req/frame_specification_parameters/sdu
^|Test Method |Inspection
|===



==== Regular Series SDU Conformance Class

[[ats_series_header_sdu]]
[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/ats/Series/header/sdu* 
^|Test Purpose |To confirm that a Series Header is implemented in accordance with the Logical Model.
^|Requirement |/req/Series/header/sdu
^|Test Method |Inspection
|===


[[ats_geoposeduration_sdu]]
[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/ats/geoposeduration/sdu* 
^|Test Purpose |To confirm that a Logical Model attribute GeoPoseduration is expressed in seconds multiplied by 1,000 and that the unit of measure is milliseconds.
^|Requirement |/req/RegularSeries/duration/sdu
^|Test Method |Inspection
|===

[[ats_frame_specification_authority_sdu]]
[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/ats/frame_specification_authority/sdu* 
^|Test Purpose |To confirm that a FrameSpecification.authority attribute contains a string uniquely specifying a source of reference frame specifications.
^|Requirement |/req/frame_specification_authority/sdu
^|Test Method |Inspection
|===

[[ats_frame_specification_id_sdu]]
[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/ats/frame_specification_id/sdu* 
^|Test Purpose |To confirm that a FrameSpecification.id attribute is a string uniquely defining a frame within the authority.
^|Requirement |/req/frame_specification_id/sdu
^|Test Method |Inspection
|===

[[ats_frame_specification_parameters_sdu]]
[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/ats/frame_specification_parameters/sdu* 
^|Test Purpose |To confirm that a FrameSpecification.parameters attribute contains contain all parameters needed for the corresponding authority and ID.
^|Requirement |/req/frame_specification_parameters/sdu
^|Test Method |Inspection
|===


[[ats_series_trailer_sdu]]
[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/ats/Series/trailer/sdu* 
^|Test Purpose |To confirm that a Series Trailer is implemented in accordance with the Logical Model.
^|Requirement |/req/Series/trailer/sdu
^|Test Method |Inspection
|===



==== Irregular Series SDU Conformance Class


[[ats_series_header_sdu]]
[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/ats/Series/header/sdu* 
^|Test Purpose |To confirm that a Series Header is implemented in accordance with the Logical Model.
^|Requirement |/req/Series/header/sdu
^|Test Method |Inspection
|===

[[ats_frame_specification_authority_sdu]]
[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/ats/frame_specification_authority/sdu* 
^|Test Purpose |To confirm that a FrameSpecification.authority attribute contains a string uniquely specifying a source of reference frame specifications.
^|Requirement |/req/frame_specification_authority/sdu
^|Test Method |Inspection
|===

[[ats_frame_specification_id_sdu]]
[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/ats/frame_specification_id/sdu* 
^|Test Purpose |To confirm that a FrameSpecification.id attribute is a string uniquely defining a frame within the authority.
^|Requirement |/req/frame_specification_id/sdu
^|Test Method |Inspection
|===

[[ats_frame_specification_parameters_sdu]]
[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/ats/frame_specification_parameters/sdu* 
^|Test Purpose |To confirm that a FrameSpecification.parameters attribute contains contain all parameters needed for the corresponding authority and ID.
^|Requirement |/req/frame_specification_parameters/sdu
^|Test Method |Inspection
|===

[[ats_series_frame_and_time_sdu]]
[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/ats/Series/frame_and_time/sdu* 
^|Test Purpose |To confirm that a Series frame_and_time is implemented as an innerFrameAndTime property with an ExplicitFrameSpec and GeoPoseInstant pair.
^|Requirement |/req/Series/frame_and_time/sdu
^|Test Method |Inspection
|===

[[ats_series_trailer_sdu]]
[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/ats/Series/trailer/sdu* 
^|Test Purpose |To confirm that a Series Trailer is implemented in accordance with the Logical Model.
^|Requirement |/req/Series/trailer/sdu
^|Test Method |Inspection
|===

==== Stream SDU Conformance Class


[[ats_transition_model_sdu]]
[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/ats/transition_model/sdu* 
^|Test Purpose |To confirm that a transition_model attribute is one of the values in the TransitionModel enumeration.
^|Requirement |/req/transition_model/sdu
^|Test Method |Inspection
|===


[[ats_frame_specification_authority_sdu]]
[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/ats/frame_specification_authority/sdu* 
^|Test Purpose |To confirm that a FrameSpecification.authority attribute contains a string uniquely specifying a source of reference frame specifications.
^|Requirement |/req/frame_specification_authority/sdu
^|Test Method |Inspection
|===

[[ats_frame_specification_id_sdu]]
[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/ats/frame_specification_id/sdu* 
^|Test Purpose |To confirm that a FrameSpecification.id attribute is a string uniquely defining a frame within the authority.
^|Requirement |/req/frame_specification_id/sdu
^|Test Method |Inspection
|===

[[ats_frame_specification_parameters_sdu]]
[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/ats/frame_specification_parameters/sdu* 
^|Test Purpose |To confirm that a FrameSpecification.parameters attribute contains contain all parameters needed for the corresponding authority and ID.
^|Requirement |/req/frame_specification_parameters/sdu
^|Test Method |Inspection
|===


[[ats_stream_frame_and_time_sdu]]
[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/ats/stream/frame_and_time/sdu* 
^|Test Purpose |To confirm that a Stream frame_and_time is implemented as an innerFrameAndTime property with an ExplicitFrameSpec and GeoPoseInstant pair.
^|Requirement |/req/Stream/fst/sdu
^|Test Method |Inspection
|===


=== Encodings

Each encoding technology has its own independent test suite. 

==== JSON Conformance

include::abstract_tests/encodings/json/ATS_Basic.adoc[]

include::abstract_tests/encodings/json/ATS_Advanced.adoc[]

include::abstract_tests/encodings/json/ATS_Composite.adoc[]

