[[annex-A]]
[appendix, obligation=normative]
== Abstract Test Suite

=== Introduction

GeoPose 1.0 specifies a eight Standardization Targets using elements of the Logical Model. These elements are Structural Data Units (SDUs) and they have the stereotype "Structural Data Unit - SDU". Each SDU is an element of the Logical Model that will be expressed in concrete data objects encoded using specific encoding or serialization technologies.

Although implementation of the Standardization Targets, expressed as SDUs, is independent of the Logical Model, GeoPose 1.0 also defines one of many possible implementations, single encoding in JavaScript Object Notation (JSON). The encodings of the eight targets are specified using <<jsonschema2019>>. To keep the individual Standardization targets independent, there are some SDU requirements and corresponding conformance tests that appear in more than one requirement or conformance class. This structure is based on the judgement that it is easier to understand the independence of targets with complete definitions than would be the case if the definitional requirements of the SDUs were factored out and referenced indirectly by individual encodings.

=== Global conformance class

Conformance with the Global Requirements is required for all implementations.

include::conf/global.adoc[]

The individual global tests are as follows.

include::conf/global/target-dependency.adoc[]

include::conf/global/sdu-general.adoc[]

include::conf/global/lm-general.adoc[]


=== Structural Data Unit (SDU) Conformance

There are some universal requirements on values that appear in a concrete implementation using a specific encoding technology. For example, angles may be constrained to fall within a range of values corresponding to a circle. Because these are independent of encoding technology, they are specified here at a logical level. Tests of an implementation at the SDU level generally only be done by inspection.

=== Basic-YPR SDU Conformance Class

include::conf/basic-ypr.adoc[]

The Basic-YPR SDU member tests are the following:

include::conf/basic-ypr/sdu.adoc[]

include::conf/basic-ypr/sdu-tangent-plane-longitude.adoc[]

include::conf/basic-ypr/sdu-tangent-plane-latitude.adoc[]

include::conf/basic-ypr/sdu-tangent-plane-h.adoc[]

include::conf/basic-ypr/sdu-orientation-ypr-angles.adoc[]


==== Basic-Quaternion SDU Conformance Class

include::conf/basic-quaternion.adoc[]

include::conf/basic-quaternion/sdu.adoc[]

include::conf/basic-quaternion/sdu-tangent-plane-longitude.adoc[]

include::conf/basic-quaternion/sdu-tangent-plane-latitude.adoc[]

include::conf/basic-quaternion/sdu-tangent-plane-h.adoc[]

include::conf/basic-quaternion/sdu-orientation_quaternion.adoc[]


==== Advanced SDU Conformance Class

include::conf/advanced.adoc[]

include::conf/advanced/sdu-time-geopose-instant.adoc[]

include::conf/advanced/sdu-frame-specification-authority.adoc[]

include::conf/advanced/sdu-frame-specification-id.adoc[]

include::conf/advanced/sdu-frame-specification-parameters.adoc[]

include::conf/advanced/sdu-orientation-quaternion.adoc[]


==== Graph SDU Conformance Class

include::conf/graph.adoc[]

include::conf/graph/sdu-time-geopose-instant.adoc[]

include::conf/graph/sdu-frame-specification-authority.adoc[]

include::conf/graph/sdu-frame-specification-id.adoc[]

include::conf/graph/sdu-frame-specification-parameters.adoc[]

include::conf/graph/index.adoc[]


==== Chain SDU Conformance Class

include::conf/chain.adoc[]

include::conf/chain/sdu-time-geopose-instant.adoc[]

include::conf/chain/sdu-frame-specification-authority.adoc[]

include::conf/chain/sdu-frame-specification-id.adoc[]

include::conf/chain/sdu-frame-specification-parameters.adoc[]

include::conf/chain/sdu-chain-index.adoc[]

==== Regular Series SDU Conformance Class

include::conf/regular-series.adoc[]

include::conf/regular-series/sdu-header.adoc[]

include::conf/regular-series/sdu-time/geopose-duration.adoc[]

include::conf/regular-series/sdu-frame-specification-authority.adoc[]

include::conf/regular-series/sdu-frame-specification-id.adoc[]

include::conf/regular-series/sdu-frame-specification-parameters.adoc[]

include::conf/regular-series/sdu-series-regular-trailer.adoc[]


==== Irregular Series SDU Conformance Class

include::conf/irregular-series.adoc[]

include::conf/irregular-series/sdu-header.adoc[]

include::conf/irregular-series/sdu-frame-specification-authority.adoc[]

include::conf/irregular-series/sdu-frame-specification-id.adoc[]

include::conf/irregular-series/sdu-frame-specification-parameters.adoc[]

include::conf/irregular-series/sdu-irregular-series-frame-and-time.adoc[]


==== Stream SDU Conformance Class

include::conf/stream.adoc[]

include::conf/stream/sdu-transition-model.adoc[]

include::conf/stream/sdu-frame-specification/authority.adoc[]

include::conf/stream/sdu-frame-specification-id.adoc[]

include::conf/stream/sdu-frame-specification-parameters.adoc[]

include::conf/stream/sdu-stream-frame-time-element.adoc[]


=== Encodings Conformance

Each encoding technology has its own independent test suite. There is one conformance class per Standardization target per encoding technology. The GeoPose Standard 1.0 has one encoding technology: JSON.

==== JSON Conformance

The *Basic-YPR GeoPose* is the JSON encoding intended for widest use.

include::conf/basic_ypr/encoding/json.adoc[]

include::conf/basic_ypr/encoding/json/test.adoc[]


The *Basic-Quaternion GeoPose* JSON encoding is intended for applications using quaternions. It comes in two sub-versions: normal and strict. The only difference is that a strict sub-version does not allow additional JSON members.

include::conf/basic-quaternion-encoding-json.adoc[]

include::conf/basic-quaternion-encoding-json/definition.adoc[]

[NOTE]
The *Basic-Quaternion (Strict) GeoPose* JSON encoding does not allow additional JSON members.

include::conf/basic-quaternion-encoding-json-strict.adoc[]

include::conf/basic-quaternion-encoding-json-strict/definition.adoc[]


The *Advanced GeoPose* JSON encoding has an optional time stamp and a flexible Outer Frame specification.

include::conf/advanced/encoding/json.adoc[]

include::conf/advanced/encoding/json/test.adoc[]

The *GeoPose Chain* JSON encoding supports a linear sequence of frame transformations for modelling articulated structures.

include::conf/chain-encoding-json.adoc[]

include::conf/chain-encoding-json/definition.adoc[]

The *GeoPose Graph* JSON encoding supports a directed graph structure.

include::conf/graph-encoding-json.adoc[]

include::conf/graph-encoding-json/definition.adoc[]

The *GeoPose Regular Series* JSON encoding supports a time series of equally-spaced GeoPoses.

include::conf/regular_series/encoding/json.adoc[]

include::conf/regular_series/encoding/json/test.adoc[]

The *GeoPose Irregular Series* JSON encoding has an optional time stamp and a flexible Outer Frame specification.

include::conf/irregular_series/encoding/json.adoc[]

include::conf/irregular_series/encoding/json/test.adoc[]

The *GeoPose Stream* JSON encoding has an optional time stamp and a flexible Outer Frame specification.

include::conf/stream/encoding/json.adoc[]

EDITOR: The following test should have been 3 tests: /req/stream-encoding-json/header,
/req/stream-encoding-json/element and /req/stream/report/encoding/json.

include::conf/stream/encoding/json/test.adoc[]
