[appendix]
:appendix-caption: Annex
[[abstract-test-suite]]
== Abstract Test Suite (Normative)

=== Introduction

GeoPose 1.0 specifies a eight Standardization Targets using elements of the Logical Model. These elements are Structural Data Units (SDUs) and they have the stereotype "Structural Data Unit - SDU". Each SDU is an element of the Logical Model that will be expressed in concrete data objects encoded using specific encoding or serialization technologies. 

Although implementation of the Standardization Targets, expressed as SDUs, is independent of the Logical Model, GeoPose 1.0 also defines one of many possible implementations, single encoding in JavaScript Object Notation (JSON). The encodings of the eight targets are specified using JSON-Schema-2019-09. To keep the individual Standardization targets independent, there are some SDU requirements and corresponding conformance tests that appear in more than one requirement or conformance class. This structure is based on the judgement that it is easier to understand the independence of targets with complete definitions than would be the case if the definitional requirements of the SDUs were factored out and referenced indirectly by individual encodings.

=== Structural Data Unit (SDU) Conformance

There are some universal requirements on values that appear in a concrete implementation using a specific encoding technology. For example, angles may be constrainted to fall within a range of values correponding to a circle. Because these are independent of encoding technology, they are specified here at a logical level. 

include::abstract_tests/structural_data_units/ATS_SDU_Basic.adoc[]

include::abstract_tests/structural_data_units/ATS_SDU_Advanced.adoc[]

include::abstract_tests/structural_data_units/ATS_SDU_Composite.adoc[]

=== Encodings

==== JSON Conformance

include::abstract_tests/encodings/json/ATS_Basic.adoc[]

include::abstract_tests/encodings/json/ATS_Advanced.adoc[]

include::abstract_tests/encodings/json/ATS_Composite.adoc[]

