[appendix]
:appendix-caption: Annex
[[abstract-test-suite]]
== Abstract Test Suite (Normative)

=== Introduction

GeoPose 1.0 specifies a eight Standardization Targets using elements of the Logical Model. These elements are Structural Data Units (SDUs) and they have the stereotype "Structural Data Unit - SDU". Each SDU is an element of the Logical Model that will be expressed in concrete data objects encoded using specific encoding or serialization technologies. 

Although implementation of the Standardization Targets, expressed as SDUs, is independent of the Logical Model, GeoPose 1.0 also defines one of many possible implementations, single encoding in JavaScript Object Notation (JSON). The encodings of the eight targets are specified using JSON-Schema-2019-09. To keep the individual Standardization targets independent, there are some SDU requirements and corresponding conformance tests that appear in more than one requirement or conformance class. This structure is based on the judgement that it is easier to understand the independence of targets with complete definitions than would be the case if the definitional requirements of the SDUs were factored out and referenced indirectly by individual encodings.

=== Global Conformance Class

Conformance with the Global Requirements is required for all implementations.

[[conf_global]]
[width="100%",%header,cols="2,6"]
|===
<|*Conformance Class:* <|*Global* 

<s|ID |<<conf_global,/conf/global>>
<s|Target Type|SDU
<s|Description| Conformance with Global SDU requirements
<s|Dependency| None
<s|Test: G-Target|/conf/target_dependency
<s|Test: G-SDU|/conf/sdu_general 
<s|Test: G-LM|/conf/lm_general 

|===

The individual global tests are:

[[conformance_global]]
[width="100%",cols="2,6"]
|===
<s|Test:  s|G-Target

<s|ID |<<conf_global,/conf/target_dependency>>
2+<|There SHALL be no dependency between or among the individual Standardization Targets.
<s|Purpose|Verify that this requirement is satisfied
<s|Method|Inspection
<s|Reference: G-Target|/req/target_dependency
<s|Test Type|Conformance
|===


[[conformance_sdu]]
[width="100%",cols="2,6"]
|===
<s|Test:  s|G-SDU



<s|ID |<<conf_sdu_general,/conf/sdu_general>>
2+<|Implementations using encoded SDUs SHALL conform to the logical description of the Logical Model elements with the "Structural Data Unit - SDU" stereotype.
<s|Purpose|Verify that this requirement is satisfied
<s|Method|Inspection
<s|Reference: G-SDU|/req/sdu_general
<s|Test Type|Conformance
|===


[[conformance_lm]]
[width="100%",cols="2,6"]
|===
<s|Test:  s|G-LM

<s|ID |<<conf_lm_general,/conf/lm_general>>
2+<|Implementations of concrete data conforming to this standard SHALL conform to all dependent or inherited classes, attributes, and associations, multiplicities, and data types in the Logical Model.
<s|Purpose|Verify that this requirement is satisfied
<s|Method|Inspection
<s|Reference: G-LM|/req/lm_general
<s|Test Type|Conformance
|===


=== Structural Data Unit (SDU) Conformance

There are some universal requirements on values that appear in a concrete implementation using a specific encoding technology. For example, angles may be constrainted to fall within a range of values correponding to a circle. Because these are independent of encoding technology, they are specified here at a logical level. Tests of an implementation at the SDU level generally only be done by inspection.

=== Basic-YPR SDU Conformance Class

[[conf_class_basic_ypr_sdu]]
[width="100%",%header,cols="3,6"]
|===
<|*Conformance Class:* <|*Basic-YPR SDU* 

<s|ID |<<conf_class_basic_ypr_sdu,/conf/class/basic_ypr_sdu>>
<s|Target Type|SDU
<s|Description|To confirm that a Basic-YPR GeoPose consists of an Outer Frame specified by an implicit WGS-84 CRS and an implicit EPSG 4461-CS (LTP-ENU) coordinate system and explicit parameters defining the tangent point and that the Inner Frame is a rotation-only transformation using Yaw, Pitch, and Roll angles.
<s|Dependency| /conf/global
<s|Test: B-YPR-SDU|/conf/basic_ypr/sdu 
<s|Test: B-TP-Lon-SDU |/conf/tangent_plane/longitude/sdu 
<s|Test: B-TP-Lat-SDU |/conf/tangent_plane/latitude/sdu 
<s|Test: B-TP-h-SDU |/conf/tangent_plane/h/sdu 
<s|Test: YPR-Angles |/conf/ypr_angles/sdu 
|===

The Basic-YPR SDU member tests are the following:

[[conf_basic_ypr_sdu]]
[width="100%",cols="3,6"]
|===
<s|Test:  s|B-YPR-SDU 

<s|ID |<</conf_basic/ypr/sdu,/conf/basic_ypr/sdu>>
2+<|To confirm that an implementation of a Basic-YPR consists of an Outer Frame specified by an implicit WGS-84 CRS and an implicit EPSG 4461-CS (LTP-ENU) coordinate system and explicit parameters to define the tangent point. To confirm that the Inner Frame is expressed as a rotation-only transformation using Yaw, Pitch, and Roll angles.
<s|Purpose|Verify that this requirement is satisfied
<s|Method|Inspection
<s|Reference: Basic-YPR-SDU|/req/basic/ypr/sdu
<s|Test Type|Conformance
|===


[[conf_tangent_plane_longitude_sdu]]
[width="100%",cols="3,6"]
|===
<s|Test:  s|B-TP-Lon-SDU 

<s|ID |<</conf_tangent_plane_longitude_sdu,/conf_tangent_plane_longitude_sdu>>
2+<|To confirm that a GeoPose tangentPoint.longitude attribute is expressed as an angle in decimal degrees.
<s|Purpose|Verify that this requirement is satisfied
<s|Method|Inspection
<s|Reference: Tangent-Plane-Longitude|/req/tangent_plane_longitude_sdu
<s|Test Type|Conformance
|===


[[conf_tangent_plane_latitude_sdu]]
[width="100%",cols="3,6"]
|===
<s|Test:  s|B-TP-Lat-SDU 

<s|ID |<</conf_tangent_plane_latitude_sdu,/conf_tangent_plane_latitude_sdu>>
2+<|To confirm that a GeoPose tangentPoint.latitude attribute is expressed as an angle in decimal degrees.
<s|Purpose|Verify that this requirement is satisfied
<s|Method|Inspection
<s|Reference: Tangent-Plane-Latitude|/req/tangent_plane_latitude_sdu
<s|Test Type|Conformance
|===


[[conf_tangent_plane_h_sdu]]
[width="100%",cols="3,6"]
|===
<s|Test:  s|B-TP-h-SDU 

<s|ID |<</conf_tangent_plane_h_sdu,/conf_tangent_plane_h_sdu>>
2+<|To confirm that a GeoPose tangentPoint.h attribute is expressed as a height in meters above the WGS-84 ellipsoid.
<s|Purpose|Verify that this requirement is satisfied
<s|Method|Inspection
<s|Reference: Tangent-Plane-h|/req/tangent_plane_h_sdu
<s|Test Type|Conformance
|===



[[conf_ypr_angles_sdu]]
[width="100%",cols="3,6"]
|===
<s|Test:  s|YPR-Angles 

<s|ID |<</conf_ypr_angles_sdu,/conf_ypr_angles_sdu>>
2+<|To confirm that GeoPose YPR angles are expressed as three consecutive rotations about the local axes Z, Y, and X, in that order, corresponding to the conventional Yaw, Pitch, and Roll angles and that the unit of measure is the degree.
<s|Purpose|Verify that this requirement is satisfied
<s|Method|Inspection
<s|Reference: YPR-Angles|/req/ypr_angles_sdu
<s|Test Type|Conformance
|===


==== Basic-Q SDU Conformance Class


[[conf_class_basic_quaternion_sdu]]
[width="100%",%header,cols="3,6"]
|===
<|*Conformance Class:* <|*Basic-Q SDU* 

<s|ID |<<conf_class/basic_quaternion_sdu,/conf/class/basic_quaternion_sdu>>
<s|Target Type|SDU
<s|Description|To confirm AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA.
<s|Dependency| /conf/global
<s|Test: B-Q-SDU|/conf/basic_quaternion/sdu 
<s|Test: B-TP-Lon-SDU |/conf/tangent_plane/longitude/sdu 
<s|Test: B-TP-Lat-SDU |/conf/tangent_plane/latitude/sdu 
<s|Test: B-TP-h-SDU |/conf/tangent_plane/h/sdu 
<s|Test: YPR-Angles |/conf/ypr_angles/sdu 
|===


[[ats_basic_quaternion_sdu]]
[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/conf/basic/quaternion/sdu* 
^|Test Purpose |To confirm that a Basic-Q GeoPose consists of an Outer Frame specified by an implicit WGS-84 CRS and an implicit EPSG 4461-CS (LTP-ENU) coordinate system and explicit parameters defining the tangent point and that the Inner Frame is a rotation-only transformation using a unit quaternion.
^|Requirement |/req/basic/quaternion/sdu
^|Test Method |Inspection
|===

[[ats_tangent_plane_longitude_sdu]]
[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/conf/tangent_plane/longitude/sdu* 
^|Test Purpose |To confirm that a GeoPose tangentPoint.longitude attribute is expressed as a real number.
^|Requirement |/req/tangent_plane/longitude/sdu
^|Test Method |Inspection
|===

[[ats_tangent_plane_latitude_sdu]]
[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/conf/tangent_plane/latitude/sdu* 
^|Test Purpose |To confirm that a GeoPose tangentPoint.latitude attribute is expressed as a real number.
^|Requirement |/req/tangent_plane/latitude/sdu
^|Test Method |Inspection
|===

[[ats_tangent_plane_h_sdu]]
[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/conf/tangent_plane/h/sdu* 
^|Test Purpose |To confirm that a GeoPose tangentPoint.h attribute is expressed as a real number.
^|Requirement |/req/tangent_plane/h/sdu
^|Test Method |Inspection
|===

[[ats_orientation_quaternion_sdu]]
[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/conf/orientation/quaternion/sdu* 
^|Test Purpose |To confirm that the unit quaternion consists of four representations of real number values and that the square root of the sum of the  squares of those numbers is approximately 1.
^|Requirement |/req/orientation/quaternion/sdu
^|Test Method |Inspection
|===

==== Advanced SDU Conformance Class

[[conf_class_advanced_sdu]]
[width="100%",%header,cols="3,6"]
|===
<|*Conformance Class:* <|*Advanced SDU* 

<s|ID |<<conf_class_advanced_sdu,/conf/class/advanced_sdu>>
<s|Target Type|SDU
<s|Description|To confirm AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA.
<s|Dependency| /conf/global
<s|Test: B-YPR-SDU|/conf/basic_ypr/sdu 
<s|Test: B-TP-Lon-SDU |/conf/tangent_plane/longitude/sdu 
<s|Test: B-TP-Lat-SDU |/conf/tangent_plane/latitude/sdu 
<s|Test: B-TP-h-SDU |/conf/tangent_plane/h/sdu 
<s|Test: YPR-Angles |/conf/ypr_angles/sdu 
|===

[[ats_geoposeinstant_sdu]]
[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/conf/geoposeinstant/sdu* 
^|Test Purpose |To confirm that a Logical Model attribute GeoPoseInstant is Unix Time in seconds multiplied by 1,000 and that the unit of measure is milliseconds.
^|Requirement |/req/geoposeinstant/sdu
^|Test Method |Inspection
|===

[[ats_frame_specification_authority_sdu]]
[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/conf/frame_specification_authority/sdu* 
^|Test Purpose |To confirm that a FrameSpecification.authority attribute contains a string uniquely specifying a source of reference frame specifications.
^|Requirement |/req/frame_specification_authority/sdu
^|Test Method |Inspection
|===

[[ats_frame_specification_id_sdu]]
[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/conf/frame_specification_id/sdu* 
^|Test Purpose |To confirm that a FrameSpecification.id attribute is a string uniquely defining a frame within the authority.
^|Requirement |/req/frame_specification_id/sdu
^|Test Method |Inspection
|===

[[ats_frame_specification_parameters_sdu]]
[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/conf/frame_specification_parameters/sdu* 
^|Test Purpose |To confirm that a FrameSpecification.parameters attribute contains contain all parameters needed for the corresponding authority and ID.
^|Requirement |/req/frame_specification_parameters/sdu
^|Test Method |Inspection
|===


[[ats_orientation_quaternion_sdu]]
[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/conf/orientation/quaternion/sdu* 
^|Test Purpose |To confirm that the unit quaternion consists of four representations of real number values and that the square root of the sum of the  squares of those numbers is approximately 1.
^|Requirement |/req/orientation/quaternion/sdu
^|Test Method |Inspection
|===

==== Graph SDU Conformance Class



[[conf_class_graph_sdu]]
[width="100%",%header,cols="3,6"]
|===
<|*Conformance Class:* <|*Graph SDU* 

<s|ID |<<conf_class_graph_sdu,/conf/class/graph_sdu>>
<s|Target Type|SDU
<s|Description|To confirm AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA.
<s|Dependency| /conf/global
<s|Test: B-YPR-SDU|/conf/basic_ypr/sdu 
<s|Test: B-TP-Lon-SDU |/conf/tangent_plane/longitude/sdu 
<s|Test: B-TP-Lat-SDU |/conf/tangent_plane/latitude/sdu 
<s|Test: B-TP-h-SDU |/conf/tangent_plane/h/sdu 
<s|Test: YPR-Angles |/conf/ypr_angles/sdu 
|===



[[ats_geoposeinstant_sdu]]
[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/conf/geoposeinstant/sdu* 
^|Test Purpose |To confirm that a Logical Model attribute GeoPoseInstant is Unix Time in seconds multiplied by 1,000 and that the unit of measure is milliseconds.
^|Requirement |/req/geoposeinstant/sdu
^|Test Method |Inspection
|===


[[ats_frame_specification_authority_sdu]]
[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/conf/frame_specification_authority/sdu* 
^|Test Purpose |To confirm that a FrameSpecification.authority attribute contains a string uniquely specifying a source of reference frame specifications.
^|Requirement |/req/frame_specification_authority/sdu
^|Test Method |Inspection
|===

[[ats_frame_specification_id_sdu]]
[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/conf/frame_specification_id/sdu* 
^|Test Purpose |To confirm that a FrameSpecification.id attribute is a string uniquely defining a frame within the authority.
^|Requirement |/req/frame_specification_id/sdu
^|Test Method |Inspection
|===

[[ats_frame_specification_parameters_sdu]]
[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/conf/frame_specification_parameters/sdu* 
^|Test Purpose |To confirm that a FrameSpecification.parameters attribute contains contain all parameters needed for the corresponding authority and ID.
^|Requirement |/req/frame_specification_parameters/sdu
^|Test Method |Inspection
|===

[[ats_chain_index_sdu]]
[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/conf/chain/index/sdu* 
^|Test Purpose |To confirm that each index vaue in a FrameListTransformPair is a distinct integer value between 0 and one less than the number of elements in the frameList property.
^|Requirement |/req/Chain/index/sdu
^|Test Method |Inspection
|===


==== Chain SDU Conformance Class


[[conf_class_chain_sdu]]
[width="100%",%header,cols="3,6"]
|===
<|*Conformance Class:* <|*Chain SDU* 

<s|ID |<<conf_class_chain_sdu,/conf/class/chain_sdu>>
<s|Target Type|SDU
<s|Description|To confirm AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA.
<s|Dependency| /conf/global
<s|Test: B-YPR-SDU|/conf/basic_ypr/sdu 
<s|Test: B-TP-Lon-SDU |/conf/tangent_plane/longitude/sdu 
<s|Test: B-TP-Lat-SDU |/conf/tangent_plane/latitude/sdu 
<s|Test: B-TP-h-SDU |/conf/tangent_plane/h/sdu 
<s|Test: YPR-Angles |/conf/ypr_angles/sdu 
|===




[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/conf/geoposeinstant/sdu* 
^|Test Purpose |To confirm that a Logical Model attribute GeoPoseInstant is Unix Time in seconds multiplied by 1,000 and that the unit of measure is milliseconds.
^|Requirement |/req/geoposeinstant/sdu
^|Test Method |Inspection
|===


[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/conf/frame_specification_authority/sdu* 
^|Test Purpose |To confirm that a FrameSpecification.authority attribute contains a string uniquely specifying a source of reference frame specifications.
^|Requirement |/req/frame_specification_authority/sdu
^|Test Method |Inspection
|===


[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/conf/frame_specification_id/sdu* 
^|Test Purpose |To confirm that a FrameSpecification.id attribute is a string uniquely defining a frame within the authority.
^|Requirement |/req/frame_specification_id/sdu
^|Test Method |Inspection
|===


[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/conf/frame_specification_parameters/sdu* 
^|Test Purpose |To confirm that a FrameSpecification.parameters attribute contains contain all parameters needed for the corresponding authority and ID.
^|Requirement |/req/frame_specification_parameters/sdu
^|Test Method |Inspection
|===



==== Regular Series SDU Conformance Class


[[conf_class_regular_series_sdu]]
[width="100%",%header,cols="3,6"]
|===
<|*Conformance Class:* <|*Regular Series SDU* 

<s|ID |<<conf_class_regular_series_sdu,/conf/class/regular_series/sdu>>
<s|Target Type|SDU
<s|Description|To confirm AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA.
<s|Dependency| /conf/global
<s|Test: B-YPR-SDU|/conf/basic_ypr/sdu 
<s|Test: B-TP-Lon-SDU |/conf/tangent_plane/longitude/sdu 
<s|Test: B-TP-Lat-SDU |/conf/tangent_plane/latitude/sdu 
<s|Test: B-TP-h-SDU |/conf/tangent_plane/h/sdu 
<s|Test: YPR-Angles |/conf/ypr_angles/sdu 
|===



[[ats_series_header_sdu]]
[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/conf/Series/header/sdu* 
^|Test Purpose |To confirm that a Series Header is implemented in accordance with the Logical Model.
^|Requirement |/req/Series/header/sdu
^|Test Method |Inspection
|===


[[ats_geoposeduration_sdu]]
[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/conf/geoposeduration/sdu* 
^|Test Purpose |To confirm that a Logical Model attribute GeoPoseDuration is expressed in seconds multiplied by 1,000 and that the unit of measure is milliseconds.
^|Requirement |/req/RegularSeries/duration/sdu
^|Test Method |Inspection
|===


[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/conf/frame_specification_authority/sdu* 
^|Test Purpose |To confirm that a FrameSpecification.authority attribute contains a string uniquely specifying a source of reference frame specifications.
^|Requirement |/req/frame_specification_authority/sdu
^|Test Method |Inspection
|===


[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/conf/frame_specification_id/sdu* 
^|Test Purpose |To confirm that a FrameSpecification.id attribute is a string uniquely defining a frame within the authority.
^|Requirement |/req/frame_specification_id/sdu
^|Test Method |Inspection
|===


[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/conf/frame_specification_parameters/sdu* 
^|Test Purpose |To confirm that a FrameSpecification.parameters attribute contains contain all parameters needed for the corresponding authority and ID.
^|Requirement |/req/frame_specification_parameters/sdu
^|Test Method |Inspection
|===


[[ats_series_trailer_sdu]]
[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/conf/Series/trailer/sdu* 
^|Test Purpose |To confirm that a Series Trailer is implemented in accordance with the Logical Model.
^|Requirement |/req/Series/trailer/sdu
^|Test Method |Inspection
|===

==== Irregular Series SDU Conformance Class

[[conf_class_irregular_series_sdu]]
[width="100%",%header,cols="3,6"]
|===
<|*Conformance Class:* <|*Irregular Series SDU* 

<s|ID |<<conf_class_irregular_series_sdu,/conf/class/irregular_series/sdu>>
<s|Target Type|SDU
<s|Description|To confirm AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA.
<s|Dependency| /conf/global
<s|Test: B-YPR-SDU|/conf/basic_ypr/sdu 
<s|Test: B-TP-Lon-SDU |/conf/tangent_plane/longitude/sdu 
<s|Test: B-TP-Lat-SDU |/conf/tangent_plane/latitude/sdu 
<s|Test: B-TP-h-SDU |/conf/tangent_plane/h/sdu 
<s|Test: YPR-Angles |/conf/ypr_angles/sdu 
|===



[[ats_series_header_sdu]]
[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/conf/Series/header/sdu* 
^|Test Purpose |To confirm that a Series Header is implemented in accordance with the Logical Model.
^|Requirement |/req/Series/header/sdu
^|Test Method |Inspection
|===

[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/conf/frame_specification_authority/sdu* 
^|Test Purpose |To confirm that a FrameSpecification.authority attribute contains a string uniquely specifying a source of reference frame specifications.
^|Requirement |/req/frame_specification_authority/sdu
^|Test Method |Inspection
|===

[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/conf/frame_specification_id/sdu* 
^|Test Purpose |To confirm that a FrameSpecification.id attribute is a string uniquely defining a frame within the authority.
^|Requirement |/req/frame_specification_id/sdu
^|Test Method |Inspection
|===

[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/conf/frame_specification_parameters/sdu* 
^|Test Purpose |To confirm that a FrameSpecification.parameters attribute contains contain all parameters needed for the corresponding authority and ID.
^|Requirement |/req/frame_specification_parameters/sdu
^|Test Method |Inspection
|===

[[ats_series_frame_and_time_sdu]]
[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/conf/Series/frame_and_time/sdu* 
^|Test Purpose |To confirm that a Series frame_and_time is implemented as an innerFrameAndTime property with an ExplicitFrameSpec and GeoPoseInstant pair.
^|Requirement |/req/Series/frame_and_time/sdu
^|Test Method |Inspection
|===

[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/conf/Series/trailer/sdu* 
^|Test Purpose |To confirm that a Series Trailer is implemented in accordance with the Logical Model.
^|Requirement |/req/Series/trailer/sdu
^|Test Method |Inspection
|===

==== Stream SDU Conformance Class


[[conf_class_stream_sdu]]
[width="100%",%header,cols="3,6"]
|===
<|*Conformance Class:* <|*Stream SDU* 

<s|ID |<<conf_class_stream_sdu,/conf/class/stream/sdu>>
<s|Target Type|SDU
<s|Description|To confirm AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA.
<s|Dependency| /conf/global
<s|Test: B-YPR-SDU|/conf/basic_ypr/sdu 
<s|Test: B-TP-Lon-SDU |/conf/tangent_plane/longitude/sdu 
<s|Test: B-TP-Lat-SDU |/conf/tangent_plane/latitude/sdu 
<s|Test: B-TP-h-SDU |/conf/tangent_plane/h/sdu 
<s|Test: YPR-Angles |/conf/ypr_angles/sdu 
|===



[[ats_transition_model_sdu]]
[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/conf/transition_model/sdu* 
^|Test Purpose |To confirm that a transition_model attribute is one of the values in the TransitionModel enumeration.
^|Requirement |/req/transition_model/sdu
^|Test Method |Inspection
|===


[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/conf/frame_specification_authority/sdu* 
^|Test Purpose |To confirm that a FrameSpecification.authority attribute contains a string uniquely specifying a source of reference frame specifications.
^|Requirement |/req/frame_specification_authority/sdu
^|Test Method |Inspection
|===

[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/conf/frame_specification_id/sdu* 
^|Test Purpose |To confirm that a FrameSpecification.id attribute is a string uniquely defining a frame within the authority.
^|Requirement |/req/frame_specification_id/sdu
^|Test Method |Inspection
|===

[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/conf/frame_specification_parameters/sdu* 
^|Test Purpose |To confirm that a FrameSpecification.parameters attribute contains contain all parameters needed for the corresponding authority and ID.
^|Requirement |/req/frame_specification_parameters/sdu
^|Test Method |Inspection
|===

[[ats_stream_frame_and_time_sdu]]
[width="90%",cols="2,6"]
|===
^|*Abstract Test {counter:ats-id}* |*/conf/stream/frame_and_time/sdu* 
^|Test Purpose |To confirm that a Stream frame_and_time is implemented as an innerFrameAndTime property with an ExplicitFrameSpec and GeoPoseInstant pair.
^|Requirement |/req/Stream/fst/sdu
^|Test Method |Inspection
|===


=== Encodings  Conformance

Each encoding technology has its own independent test suite. There is one cornformance class per Standardization target per encoding technology. The GeoPose Standard 1.0 has one encoding technology: JSON.

==== JSON Conformance

The *Basic-YPR GeoPose* is the JSON encoding intended for widest use.

[[conf_class_basic_ypr_encoding_json]]
[width="100%",%header,cols="3,6"]
|===
<|*Conformance Class:* <|*Basic-YPR Encoding-JSON* 

<s|ID |<<conf_class_basic_ypr_encoding_json,/conf/class/basic_ypr_encoding_json>>
<s|Target Type|JSON object
<s|Description|To confirm that a Basic-YPR GeoPose consists of an Outer Frame specified by an implicit WGS-84 CRS and an implicit EPSG 4461-CS (LTP-ENU) coordinate system and explicit parameters defining the tangent point and that the Inner Frame is a rotation-only transformation using Yaw, Pitch, and Roll angles.
<s|Dependency| /conf/basic_ypr_sdu
<s|Test: B-YPR-Encoding-JSON|/conf/basic_ypr/encoding/json 

|===

The Basic-YPR JSON Encoding member test is the following:

[[conf_basic_ypr_encoding_json_test]]
[width="100%",cols="3,6"]
|===
<s|Test:  s|B-YPR-Encoding-JSON 

<s|ID |<</conf_basic/ypr/encoding/json/test,/conf/basic_ypr/encoding/json/test>>
2+<|To confirm that a JSON encoding of a Basic-YPR GeoPose conforms with the corresponding JSON-Schema definition.
<s|Purpose|To confirm that Basic-YPR GeoPose data objects conform to the Basic-YPR JSON-Schema definition.
<s|Method|JSON-Schema validation.
<s|Reference: Basic-YPR-SDU|/req/basic/ypr/sdu
<s|Test Type|Conformance
|===

The *Basic-Quaternion GeoPose* JSON encoding is intended for applications using quaternions. It comes in two sub-versions: normal and strict. The only difference is that a strict sub-version does not allow additional JSON members.

[[conf_basic_quaternion_encoding_json]]
[width="100%",%header,cols="3,6"]
|===
<|*Conformance Class:* <|*Basic-Quaternion Encoding-JSON* 

<s|ID |<<conf_class_basic_ypr_encoding_json,/conf/class/basic_ypr_encoding_json>>
<s|Target Type|JSON object
<s|Description|To confirm that a Basic-YPR GeoPose consists of an Outer Frame specified by an implicit WGS-84 CRS and an implicit EPSG 4461-CS (LTP-ENU) coordinate system and explicit parameters defining the tangent point and that the Inner Frame is a rotation-only transformation using Yaw, Pitch, and Roll angles.
<s|Dependency| /conf/basic_ypr_sdu
<s|Test: B-YPR-Encoding-JSON|/conf/basic_ypr/encoding/json/test 

|===

The *Basic-Quaternion* JSON Encoding member test is the following:

[[conf_basic_quaternion_encoding_json_test]]
[width="100%",cols="3,6"]
|===
<s|Test:  s|B-Quaternion-Encoding-JSON 

<s|ID |<</conf/basic_ypr/encoding/json/test,/conf/basic_ypr/encoding/json/test>>
2+<|To confirm that an implementation of a Basic-YPR consists of an Outer Frame specified by an implicit WGS-84 CRS and an implicit EPSG 4461-CS (LTP-ENU) coordinate system and explicit parameters to define the tangent point. To confirm that the Inner Frame is expressed as a rotation-only transformation using Yaw, Pitch, and Roll angles.
<s|Purpose|To confirm that Basic-YPR GeoPose data objects conform to the Basic-YPR JSON-Schema definition.
<s|Method|JSON-Schema validation.
<s|Reference: Basic-YPR-SDU|/req/basic/ypr/sdu
<s|Test Type|Conformance
|===

|===
|===

[NOTE]
The *Basic-Quaternion (Strict) GeoPose* JSON encoding does not allow additional JSON members.

[[conf_class_basic_quaternion_encoding_json ]]
[width="100%",%header,cols="3,6"]
|===
<|*Conformance Class:* <|*Basic-Quaternion Encoding-JSON (Strict)* 

<s|ID |<<conf_class_basic_quaternion_encoding_json_strict,/conf/class/quaternion/encoding/json_strict>>
<s|Target Type|JSON object
<s|Description|To confirm that a Basic-Quaternion GeoPose (Strict) consists of an Outer Frame specified by an implicit WGS-84 CRS and an implicit EPSG 4461-CS (LTP-ENU) coordinate system and explicit parameters defining the tangent point and that the Inner Frame is a rotation-only transformation using Yaw, Pitch, and Roll angles.
<s|Dependency| /conf/basic_ypr_sdu
<s|Test: B-Quaternion-Encoding-JSON-Strict|/conf/basic_ypr/encoding/json 

|===

The Basic-Quaternion JSON (Strict) Encoding member test is the following:

[[conf_basic_quaternion_encoding_json_strict]]
[width="100%",cols="3,6"]
|===
<s|Test:  s|B-YPR-Encoding-JSON (Strict)

<s|ID |<</conf_basic/ypr/encoding/json_strict,/conf/basic_ypr/encoding/json_strict>>
2+<|To confirm that an implementation of a Basic-YPR consists of an Outer Frame specified by an implicit WGS-84 CRS and an implicit EPSG 4461-CS (LTP-ENU) coordinate system and explicit parameters to define the tangent point. To confirm that the Inner Frame is expressed as a rotation-only transformation using Yaw, Pitch, and Roll angles.
<s|Purpose|To confirm that Basic-Quaternion (Strict) GeoPose data objects conform to the Basic-Quaternion (Strict) JSON-Schema definition.
<s|Method|JSON-Schema validation.
<s|Reference: Basic-YPR-SDU|/req/basic/ypr/sdu
<s|Test Type|Conformance
|===

|===
|===

The *Advanced GeoPose* JSON encoding has an optional time stamp and a flexible Outer Frame specification.

[[conf_class_advanced_encoding_json]]
[width="100%",%header,cols="3,6"]
|===
<|*Conformance Class:* <|*Advanced Encoding-JSON* 

<s|ID |<<conf_class_advanced_encoding_json,/conf/class/advanced/encoding/json>>
<s|Target Type|JSON object
<s|Description|To confirm that a JSON-encoded Advanced GeoPose conforms to the relevant elements of the Logical Model and a specific JSON-Schema document.
<s|Dependency| /conf/advanced_sdu
<s|Test: Advanced-Encoding-JSON|/conf/advanced/encoding/json/test 

|===

The *Advanced GeoPose* JSON Encoding member test is the following:

[[conf_advanced_encoding_json_test]]
[width="100%",cols="3,6"]
|===
<s|Test:  s|Advanced-Encoding-JSON 

<s|ID |<<conf_advanced_encoding_json_test,/conf/advanced/encoding/json/test>>
2+<|Confirm that a JSON-encoded Advanced GeoPose conforms to the specified JSON-Schema document.
<s|Purpose|To confirm that Basic-YPR GeoPose data objects conform to the Basic-YPR JSON-Schema definition.
<s|Method|JSON-Schema validation.
<s|Reference: Advanced-SDU|/req/advanced/sdu
<s|Test Type|Conformance
|===


|===
|===

The *GeoPose Chain* JSON encoding supports a linear sequence of frame transformations for modelling articulated structures.

[[conf_class_chain_encoding_json]]
[width="100%",%header,cols="3,6"]
|===
<|*Conformance Class:* <|*Chain Encoding-JSON* 

<s|ID |<<conf_class_chain_encoding_json,/conf/class/chain/encoding/json>>
<s|Target Type|JSON object
<s|Description|To confirm that a JSON-encoded GeoPose Chain conforms to the relevant elements of the Logical Model and a specific JSON-Schema document.
<s|Dependency| /conf/chain/sdu
<s|Test: Chain-Encoding-JSON|/conf/chain/encoding/json/test 

|===

The Chain Encoding member test is the following:

[[conf_chain_encoding_json_test]]
[width="100%",cols="3,6"]
|===
<s|Test:  s|Chain-Encoding-JSON 

<s|ID |<<conf_chain_encoding_json,/conf/chain/encoding/json>>
2+<|Confirm that a JSON-encoded GeoPose Chain conforms to the specified JSON-Schema document.
<s|Purpose|To confirm that Chain GeoPose data objects conform to the Chain JSON-Schema definition.
<s|Method|JSON-Schema validation.
<s|Reference: Chain-Encoding-JSON|/req/chain/sdu
<s|Test Type|Conformance
|===



The *GeoPose Graph* JSON encoding supports a directed graph stucture.

[[conf_class_graph_encoding_json]]
[width="100%",%header,cols="3,6"]
|===
<|*Conformance Class:* <|*Graph Encoding-JSON* 

<s|ID |<<conf_class_graph_encoding_json,/conf/class/graph/encoding/json>>
<s|Target Type|JSON object
<s|Description|To confirm that a JSON-encoded GeoPose Graph conforms to the relevant elements of the Logical Model and a specific JSON-Schema document. 
<s|Dependency| /conf/graph/sdu
<s|Test: Graph-Encoding-JSON|/conf/graph/encoding/json/test 

|===

The Graph Encoding member test is the following:

[[conf_graph_encoding_json_test]]
[width="100%",cols="3,6"]
|===
<s|Test:  s|Graph-Encoding-JSON 

<s|ID |<<conf_graph_encoding_json_test,/conf/graph/encoding/json/test>>
2+<|To confirm that GeoPose Graph data objects conform to the Graph JSON-Schema definition.
<s|Purpose|To confirm that Graph GeoPose data objects conform to the Graph JSON-Schema definition.
<s|Method|JSON-Schema validation.
<s|Reference: Graph-Encoding-JSON|/req/graph/sdu
<s|Test Type|Conformance
|===

|===
|===

The *GeoPose Regular Series* JSON encoding supports a time series of equally-spaced GeoPoses.

[[conf_class_regular_series_encoding_json]]
[width="100%",%header,cols="3,6"]
|===
<|*Conformance Class:* <|*GeoPose Regular Series* Encoding-JSON* 

<s|ID |<<conf_class_regular_series_encoding_json,/conf/class/regular_series_encoding_json>>
<s|Target Type|JSON object
<s|Description|To confirm that a JSON-encoded Regular Series conforms to the relevant elements of the Logical Model and a specific JSON-Schema document.
<s|Dependency| /conf/regular_series/sdu
<s|Test: B-Quaternion-Encoding-JSON-Strict|/conf/basic_ypr/encoding/json 

|===

The *GeoPose Regular Series* JSON Encoding member test is the following:

[[conf_regular_series_encoding_json]]
[width="100%",cols="3,6"]
|===
<s|Test:  s|GeoPose Regular Series-Encoding-JSON 

<s|ID |<</conf_basic/ypr/encoding/json,/conf/basic_ypr/encoding/json>>
2+<|To confirm that an implementation of a Basic-YPR consists of an Outer Frame specified by an implicit WGS-84 CRS and an implicit EPSG 4461-CS (LTP-ENU) coordinate system and explicit parameters to define the tangent point. To confirm that the Inner Frame is expressed as a rotation-only transformation using Yaw, Pitch, and Roll angles.
<s|Purpose|To confirm that Basic-YPR GeoPose data objects conform to the Basic-YPR JSON-Schema definition.
<s|Method|JSON-Schema validation.
<s|Reference: Basic-YPR-SDU|/req/basic/ypr/sdu
<s|Test Type|Conformance
|===


|===
|===

The *GeoPose Irregular Series* JSON encoding has an optional time stamp and a flexible Outer Frame specification.


[[conf_class_irregular_series_encoding_json]]
[width="100%",%header,cols="3,6"]
|===
<|*Conformance Class:* <|*Irregular Series* Encoding-JSON* 

<s|ID |<<conf_basic_quaternion_encoding_json,/quaternion_encoding_json_strict>>
<s|Target Type|JSON object
<s|Description|To confirm that a JSON-encoded Irregular Series conforms to the relevant elements of the Logical Model and a specific JSON-Schema document.
<s|Dependency| /conf/basic_ypr_sdu
<s|Test: Chain|/conf/basic_ypr/encoding/json 

|===

The *GeoPose Irregular Series* JSON Encoding member test is the following:

[[conf_basic_quaternion_encoding_json_strict]]
[width="100%",cols="3,6"]
|===
<s|Test:  s|Series-Irregular-Encoding-JSON 

<s|ID |<</conf_basic/ypr/encoding/json,/conf/basic_ypr/encoding/json>>
2+<|To confirm that an implementation of a Basic-YPR consists of an Outer Frame specified by an implicit WGS-84 CRS and an implicit EPSG 4461-CS (LTP-ENU) coordinate system and explicit parameters to define the tangent point. To confirm that the Inner Frame is expressed as a rotation-only transformation using Yaw, Pitch, and Roll angles.
<s|Purpose|To confirm that Basic-YPR GeoPose data objects conform to the Basic-YPR JSON-Schema definition.
<s|Method|JSON-Schema validation.
<s|Reference: Series-Irregular|/req/basic/ypr/sdu
<s|Test Type|Conformance
|===


|===
|===

The *GeoPose Stream* JSON encoding has an optional time stamp and a flexible Outer Frame specification.


[[conf_stream_encoding_json]]
[width="100%",%header,cols="3,6"]
|===
<|*Conformance Class:* <|*Stream Encoding-JSON (Strict)* 

<s|ID |<<conf_basic_quaternion_encoding_json_strict,/quaternion_encoding_json_strict>>
<s|Target Type|JSON object
<s|Description|To confirm that a Basic-Quaternion GeoPose (Strict) consists of an Outer Frame specified by an implicit WGS-84 CRS and an implicit EPSG 4461-CS (LTP-ENU) coordinate system and explicit parameters defining the tangent point and that the Inner Frame is a rotation-only transformation using Yaw, Pitch, and Roll angles.
<s|Dependency| /conf/basic_ypr_sdu
<s|Test: Stream-Encoding-JSON-Strict|/conf/basic_ypr/encoding/json 

|===

The *GeoPose Stream* JSON Encoding member test is the following:

[[conf_stream_encoding_json_test]]
[width="100%",cols="3,6"]
|===
<s|Test:  s|Stream-Encoding-JSON 

<s|ID |<</conf_basic/ypr/encoding/json,/conf/basic_ypr/encoding/json>>
2+<|To confirm that an implementation of a Basic-YPR consists of an Outer Frame specified by an implicit WGS-84 CRS and an implicit EPSG 4461-CS (LTP-ENU) coordinate system and explicit parameters to define the tangent point. To confirm that the Inner Frame is expressed as a rotation-only transformation using Yaw, Pitch, and Roll angles.
<s|Purpose|To confirm that Basic-YPR GeoPose data objects conform to the Basic-YPR JSON-Schema definition.
<s|Method|JSON-Schema validation.
<s|Reference: Stream JSON|/req/basic/ypr/sdu
<s|Test Type|Conformance
|===


|===
|===



