[[annex-A]]
[appendix, obligation=normative]
== Abstract Test Suite

=== Introduction

GeoPose 1.0 specifies a eight Standardization Targets using elements of the Logical
Model. These elements are Structural Data Units (SDUs) and they have the stereotype
"Structural Data Unit - SDU". Each SDU is an element of the Logical Model that will
be expressed in concrete data objects encoded using specific encoding or
serialization technologies.

Although implementation of the Standardization Targets, expressed as SDUs, is
independent of the Logical Model, GeoPose 1.0 also defines one of many possible
implementations, single encoding in JavaScript Object Notation (JSON). The encodings
of the eight targets are specified using JSON-Schema-2019-09. To keep the individual
Standardization targets independent, there are some SDU requirements and
corresponding conformance tests that appear in more than one requirement or
conformance class. This structure is based on the judgement that it is easier to
understand the independence of targets with complete definitions than would be the
case if the definitional requirements of the SDUs were factored out and referenced
indirectly by individual encodings.

=== Global Conformance Class

Conformance with the Global Requirements is required for all implementations.

[[conf_global]]
[conformance_class]
====
[%metadata]
label:: /conf/global
subject:: <<rc_global,Requirement Class "Global">>
classification:: Target Type:SDU
description:: Conformance with Global SDU requirements
inherit:: None

[conformance_test]
======
[%metadata]
label:: /conf/target_dependency
subject:: <<global,Requirement "Target Dependency">>
name:: G-Target
======

[conformance_test]
======
[%metadata]
label:: /conf/sdu_general
name:: G-SDU
======

[conformance_test]
======
[%metadata]
label:: /conf/lm_general
name:: G-LM
======
====

The individual global tests are:

[[conformance_global]]
[conformance_test]
====
[%metadata]
name:: G-Target
label:: /conf/target_dependency
description:: There SHALL be no dependency between or among the individual
Standardization Targets.
test-purpose:: Verify that this requirement is satisfied
test-method:: Inspection
reference:: <<global,/req/target_dependency>>
classification:: Test Type:Conformance
====

[[conformance_sdu]]
[conformance_test]
====
[%metadata]
name:: G-SDU
label:: /conf/sdu_general
description:: Implementations using encoded SDUs SHALL conform to the logical
description of the Logical Model elements with the "Structural Data Unit - SDU"
stereotype.
test-purpose:: Verify that this requirement is satisfied
test-method:: Inspection
reference:: <<sdu_confomance,/req/sdu_general>>
classification:: Test Type:Conformance
====

[[conformance_lm]]
[conformance_test]
====
[%metadata]
name:: G-LM
label:: /conf/lm_general
description:: Implementations of concrete data conforming to this standard SHALL
conform to all dependent or inherited classes, attributes, and associations,
multiplicities, and data types in the Logical Model.
test-purpose:: Verify that this requirement is satisfied
test-method:: Inspection
reference:: <<lm_confomance,/req/lm_general>>
classification:: Test Type:Conformance
====

=== Structural Data Unit (SDU) Conformance

There are some universal requirements on values that appear in a concrete
implementation using a specific encoding technology. For example, angles may be
constrained to fall within a range of values corresponding to a circle. Because these
are independent of encoding technology, they are specified here at a logical level.
Tests of an implementation at the SDU level generally only be done by inspection.

=== Basic-YPR SDU Conformance Class

[[conf_class_basic_ypr_sdu]]
[conformance_class]
====
[%metadata]
name:: Basic-YPR SDU
label:: /conf/class/basic_ypr/sdu
subject:: <<req_class_basic_ypr_sdu,Requirements Class "Basic YPR SDU">>
classification:: Target Type:SDU
description:: To confirm that a Basic-YPR GeoPose consists of an Outer Frame
specified by an implicit WGS-84 CRS and an implicit EPSG 4461-CS (LTP-ENU) coordinate
system and explicit parameters defining the tangent point and that the Inner Frame is
a rotation-only transformation using Yaw, Pitch, and Roll angles.
inherit:: /conf/global

[conformance_test,label="/conf/basic_ypr/sdu",name="B-YPR-SDU"]
======
======

[conformance_test,label="/conf/tangent_plane/longitude/sdu",name="B-TP-Lon-SDU"]
======
======

[conformance_test,label="/conf/tangent_plane/latitude/sdu",name="B-TP-Lat-SDU"]
======
======

[conformance_test,label="/conf/tangent_plane/h/sdu",name="B-TP-h-SDU"]
======
======

[conformance_test,label="/conf/ypr_angles/sdu",name="YPR-Angles-SDU"]
======
======
====

The Basic-YPR SDU member tests are the following:

[[conf_basic_ypr_sdu]]
[conformance_test]
====
[%metadata]
name:: B-YPR-SDU
label:: /conf/basic_ypr/sdu
description:: To confirm that an implementation of a Basic-YPR consists of an Outer
Frame specified by an implicit WGS-84 CRS and an implicit EPSG 4461-CS (LTP-ENU)
coordinate system and explicit parameters to define the tangent point. To confirm
that the Inner Frame is expressed as a rotation-only transformation using Yaw, Pitch,
and Roll angles.
test-purpose:: Verify that this requirement is satisfied
test-method:: Inspection
reference:: /req/basic_ypr/sdu
classification:: Test Type:Conformance
====

[[conf_tangent_plane_longitude_sdu]]
[conformance_test]
====
[%metadata]
name:: B-TP-Lon-SDU
label:: /conf/tangent_plane_longitude/sdu
description:: To confirm that a GeoPose tangentPoint.longitude attribute is expressed
as an angle in decimal degrees.
test-purpose:: Verify that this requirement is satisfied
test-method:: Inspection
reference:: /req/tangent_plane_longitude/sdu
classification:: Test Type:Conformance
====

[[conf_tangent_plane_latitude_sdu]]
[conformance_test]
====
[%metadata]
name:: B-TP-Lat-SDU
label:: /conf/tangent_plane_latitude/sdu
description:: To confirm that a GeoPose tangentPoint.latitude attribute is expressed
as an angle in decimal degrees.
test-purpose:: Verify that this requirement is satisfied
test-method:: Inspection
reference:: /req/tangent_plane_latitude/sdu
classification:: Test Type:Conformance
====

[[conf_tangent_plane_h_sdu]]
[conformance_test]
====
[%metadata]
name:: B-TP-h-SDU
label:: /conf/tangent_plane_h/sdu
description:: To confirm that a GeoPose tangentPoint.h attribute is expressed as a
height in meters above the WGS-84 ellipsoid.
test-purpose:: Verify that this requirement is satisfied
test-method:: Inspection
reference:: /req/tangent_plane_h/sdu
classification:: Test Type:Conformance
====

[[conf_ypr_angles_sdu]]
[conformance_test]
====
[%metadata]
name:: YPR-Angles-SDU
label:: /conf/ypr_angles/sdu
description:: To confirm that GeoPose YPR angles are expressed as three consecutive
rotations about the local axes Z, Y, and X, in that order, corresponding to the
conventional Yaw, Pitch, and Roll angles and that the unit of measure is the degree.
test-purpose:: Verify that this requirement is satisfied
test-method:: Inspection
reference:: /req/ypr_angles/sdu
classification:: Test Type:Conformance
====

==== Basic-Q SDU Conformance Class

[[conf_class_basic_quaternion_sdu]]
[conformance_class]
====
[%metadata]
name:: Basic-Q SDU
label:: /conf/class/basic_quaternion_sdu
subject:: <<req_basic_quaternion_sdu,Requirements Class "Basic Quaternion SDU">>
classification:: Target Type:SDU
description:: To confirm that components of a Basic Quaternion GeoPose conform to the
Logical Model.
inherit:: /conf/global

[abstract_test,label="/conf/basic_quaternion/sdu"]
======
======

[conformance_test,label="/conf/tangent_plane/longitude/sdu",name="B-TP-Lon-SDU"]
======
======

[conformance_test,label="/conf/tangent_plane/latitude/sdu",name="B-TP-Lat-SDU"]
======
======

[conformance_test,label="/conf/tangent_plane/h/sdu",name="B-TP-h-SDU"]
======
======

[conformance_test,label="/conf/quaternion/sdu",name="Quaternion-SDU"]
======
======
====

[[conf_basic_quaternion_sdu]]
[abstract_test]
====
[%metadata]
label:: /conf/basic/quaternion/sdu
test-purpose:: To confirm that a Basic-Q GeoPose consists of an Outer Frame specified by
an implicit WGS-84 CRS and an implicit EPSG 4461-CS (LTP-ENU) coordinate system and
explicit parameters defining the tangent point and that the Inner Frame is a
rotation-only transformation using a unit quaternion.
inherit:: /req/basic/quaternion/sdu
test-method:: Inspection
====

[conformance_test]
====
[%metadata]
name:: B-TP-Lon-SDU
label:: /conf/tangent_plane_longitude/sdu
description:: To confirm that a GeoPose tangentPoint.longitude attribute is expressed
as an angle in decimal degrees.
test-purpose:: Verify that this requirement is satisfied
test-method:: Inspection
reference:: /req/tangent_plane_longitude/sdu
classification:: Test Type:Conformance
====

[conformance_test]
====
[%metadata]
name:: B-TP-Lat-SDU
label:: /conf/tangent_plane_latitude/sdu
description:: To confirm that a GeoPose tangentPoint.latitude attribute is expressed
as an angle in decimal degrees.
test-purpose:: Verify that this requirement is satisfied
test-method:: Inspection
reference:: /req/tangent_plane_latitude/sdu
classification:: Test Type:Conformance
====

[conformance_test]
====
[%metadata]
name:: B-TP-h-SDU
label:: /conf/tangent_plane_h/sdu
description:: To confirm that a GeoPose tangentPoint.h attribute is expressed as a
height in meters above the WGS-84 ellipsoid.
test-purpose:: Verify that this requirement is satisfied
test-method:: Inspection
reference:: /req/tangent_plane_h/sdu
classification:: Test Type:Conformance
====

[[conf_quaternion_sdu]]
[conformance_test]
====
[%metadata]
name:: Quaternion-SDU
label:: /conf/quaternion/sdu
description:: To confirm the correct properties of a quaternion.
test-purpose:: To confirm that the unit quaternion consists of four representations of
real number values and that the square root of the sum of the squares of those
numbers is approximately 1.
reference:: /req/quaternion/sdu
test-method:: Inspection
====

==== Advanced SDU Conformance Class

[[conf_class_advanced_sdu]]
[conformance_class]
====
[%metadata]
name:: Advanced SDU
label:: /conf/class/advanced/sdu
subject:: <<req_advanced_sdu,Requirements Class "Basic Advanced SDU">>
classification:: Target Type:SDU
description:: To confirm that an implementation of the Advanced GeoPose conforms to
the Logical Model.
inherit:: /conf/global

[conformance_test,label="/conf/geopose_instant/sdu",name="GP-Instant-SDU"]
======
======

[conformance_test,label="/conf/frame_specification_authority/sdu",name="FS-Authority-SDU"]
======
======

[conformance_test,label="/conf/frame_specification_id/sdu",name="FS-ID-SDU"]
======
======

[conformance_test,label="/conf/frame_specification_parameters/sdu",name="FS-Parameters-SDU"]
======
======

[conformance_test,label="/conf/quaternion/sdu",name="Quaternion-SDU"]
======
======
====

[[conf_geopose_instant_sdu]]
[conformance_test]
====
[%metadata]
name:: GP-Instant-SDU
label:: /conf/geopose_instant/sdu
description:: To confirm the correct properties of a GeoPose Instant.
test-purpose:: To confirm that a Logical Model attribute GeoPoseInstant is Unix Time in
seconds multiplied by 1,000 and that the unit of measure is milliseconds.
reference:: /req/geopose_instant/sdu
test-method:: Inspection
====

[[conf_frame_specification_authority_sdu]]
[conformance_test]
====
[%metadata]
name:: FS-Authority-SDU
label:: /conf/frame_specification_authority/sdu
description:: To confirm the correct properties of a Frame Specification Authority.
test-purpose:: To confirm that a FrameSpecification.authority attribute contains a string
uniquely specifying a source of reference frame specifications.
reference:: /req/frame_specification_authority/sdu
test-method:: Inspection
====

[[conf_frame_specification_id_sdu]]
[conformance_test]
====
[%metadata]
name:: FS-ID-SDU
label:: /conf/frame_specification_id/sdu
description:: To confirm the correct properties of a Frame Specification ID.
test-purpose:: To confirm that a FrameSpecification.id attribute contains a string
uniquely specifying the identity of a reference frame specification as defined by
that authority.
reference:: /req/frame_specification_id/sdu
test-method:: Inspection
====

[[conf_frame_specification_parameters_sdu]]
[conformance_test]
====
[%metadata]
name:: FS-Parameters-SDU
label:: /conf/frame_specification_parameters/sdu
description:: To confirm the correct properties of Frame Specification Parameters.
test-purpose:: To confirm that a FrameSpecification.parameters attribute contains contain
all parameters needed for the corresponding authority and ID.
reference:: /req/frame_specification_parameters/sdu
test-method:: Inspection
====

[conformance_test]
====
[%metadata]
name:: Quaternion-SDU
label:: /conf/quaternion/sdu
description:: To confirm the correct properties of a quaternion.
test-purpose:: To confirm that the unit quaternion consists of four representations of
real number values and that the square root of the sum of the squares of those
numbers is approximately 1.
reference:: /req/quaternion/sdu
test-method:: Inspection
====

==== Graph SDU Conformance Class

[[conf_class_graph_sdu]]
[conformance_class]
====
[%metadata]
name:: Graph SDU
label:: /conf/class/graph/sdu
subject:: <<req_graph_sdu,Requirements Class "Graph SDU">>
classification:: Target Type:SDU
description:: To confirm that an implementation of the GeoPose Graph conforms to the
Logical Model.
inherit:: /conf/global

[conformance_test,label="/conf/geopose_instant/sdu",name="GP-Instant-SDU"]
======
======

[conformance_test,label="/conf/frame_specification_authority/sdu",name="FS-Authority-SDU"]
======
======

[conformance_test,label="/conf/frame_specification_id/sdu",name="FS-ID-SDU"]
======
======

[conformance_test,label="/conf/frame_specification_parameters/sdu",name="FS-Parameters-SDU"]
======
======

[conformance_test,label="/conf/graph_index/sdu",name="Graph-Index-SDU"]
======
======
====

[conformance_test]
====
[%metadata]
name:: GP-Instant-SDU
label:: /conf/geopose_instant/sdu
description:: To confirm the correct properties of a GeoPose Instant.
test-purpose:: To confirm that a Logical Model attribute GeoPoseInstant is Unix Time in
seconds multiplied by 1,000 and that the unit of measure is milliseconds.
reference:: /req/geopose_instant/sdu
test-method:: Inspection
====

[conformance_test]
====
[%metadata]
name:: FS-Authority-SDU
label:: /conf/frame_specification_authority/sdu
description:: To confirm the correct properties of a Frame Specification Authority.
test-purpose:: To confirm that a FrameSpecification.authority attribute contains a string
uniquely specifying a source of reference frame specifications.
reference:: /req/frame_specification_authority/sdu
test-method:: Inspection
====

[conformance_test]
====
[%metadata]
name:: FS-ID-SDU
label:: /conf/frame_specification_id/sdu
description:: To confirm the correct properties of a Frame Specification ID.
test-purpose:: To confirm that a FrameSpecification.id attribute contains a string
uniquely specifying the identity of a reference frame specification as defined by
that authority.
reference:: /req/frame_specification_id/sdu
test-method:: Inspection
====

[conformance_test]
====
[%metadata]
name:: FS-Parameters-SDU
label:: /conf/frame_specification_parameters/sdu
description:: To confirm the correct properties of Frame Specification Parameters.
test-purpose:: To confirm that a FrameSpecification.parameters attribute contains contain
all parameters needed for the corresponding authority and ID.
reference:: /req/frame_specification_parameters/sdu
test-method:: Inspection
====

[conformance_test]
====
[%metadata]
name:: Graph-Index-SDU
label:: /conf/graph_index/sdu
description:: To confirm that an implementation of Graph Index conforms to the
Logical Model.
test-purpose:: To confirm that each index value in a FrameListTransformPair is a distinct
integer value between 0 and one less than the number of elements in the frameList
property.
reference:: /req/graph_index/sdu
test-method:: Inspection
====

==== Chain SDU Conformance Class

[[conf_class_chain_sdu]]
[conformance_class]
====
[%metadata]
name:: Chain SDU
label:: /conf/class/chain_sdu
subject:: <<req_chain_sdu,Requirements Class "Chain SDU">>
classification:: Target Type:SDU
description:: To confirm that an implementation of the GeoPose Chain conforms to the
Logical Model.
inherit:: /conf/global

[conformance_test,label="/conf/geopose_instant/sdu",name="GP-Instant-SDU"]
======
======

[conformance_test,label="/conf/frame_specification_authority/sdu",name="FS-Authority-SDU"]
======
======

[conformance_test,label="/conf/frame_specification_id/sdu",name="FS-ID-SDU"]
======
======

[conformance_test,label="/conf/frame_specification_parameters/sdu",name="FS-Parameters-SDU"]
======
======

[conformance_test,label="/conf/chain_index/sdu",name="Chain-Index-SDU"]
======
======
====

[conformance_test]
====
[%metadata]
name:: GP-Instant-SDU
label:: /conf/geopose_instant/sdu
description:: To confirm the correct properties of a GeoPose Instant.
test-purpose:: To confirm that a Logical Model attribute GeoPoseInstant is Unix Time in
seconds multiplied by 1,000 and that the unit of measure is milliseconds.
reference:: /req/geopose_instant/sdu
test-method:: Inspection
====

[conformance_test]
====
[%metadata]
name:: FS-Authority-SDU
label:: /conf/frame_specification_authority/sdu
description:: To confirm the correct properties of a Frame Specification Authority.
test-purpose:: To confirm that a FrameSpecification.authority attribute contains a string
uniquely specifying a source of reference frame specifications.
reference:: /req/frame_specification_authority/sdu
test-method:: Inspection
====

[conformance_test]
====
[%metadata]
name:: FS-ID-SDU
label:: /conf/frame_specification_id/sdu
description:: To confirm the correct properties of a Frame Specification ID.
test-purpose:: To confirm that a FrameSpecification.id attribute contains a string
uniquely specifying the identity of a reference frame specification as defined by
that authority.
reference:: /req/frame_specification_id/sdu
test-method:: Inspection
====

[conformance_test]
====
[%metadata]
name:: FS-Parameters-SDU
label:: /conf/frame_specification_parameters/sdu
description:: To confirm the correct properties of Frame Specification Parameters.
test-purpose:: To confirm that a FrameSpecification.parameters attribute contains contain
all parameters needed for the corresponding authority and ID.
reference:: /req/frame_specification_parameters/sdu
test-method:: Inspection
====

[conformance_test]
====
[%metadata]
name:: Chain-Index-SDU
label:: /conf/chain_index/sdu
description:: To confirm that an implementation of Chain Index conforms to the
Logical Model.
test-purpose:: To confirm that each index value is a distinct integer value between 0 and
one less than the number of elements in the frameList property.
reference:: /req/chain_index/sdu
test-method:: Inspection
====

==== Regular Series SDU Conformance Class

[[conf_class_regular_series_sdu]]
[conformance_class]
====
[%metadata]
name:: Regular Series SDU
label:: /conf/class/regular_series/sdu
subject:: <<req_regular_series_sdu,Requirements Class "Regular Series SDU">>
classification:: Target Type:SDU
description:: To confirm that components of a Regular Series conform to the Logical
Model.
inherit:: /conf/global

[conformance_test,label="/conf/series_header/sdu",name="Series-Header-SDU"]
======
======

[conformance_test,label="/conf/geopose_duration/sdu",name="GP-Duration-SDU"]
======
======

[conformance_test,label="/conf/frame_specification_authority/sdu",name="FS-Authority-SDU"]
======
======

[conformance_test,label="/conf/frame_specification_id/sdu",name="FS-ID-SDU"]
======
======

[conformance_test,label="/conf/frame_specification_parameters/sdu",name="FS-Parameters-SDU"]
======
======

[conformance_test,label="/conf/series_trailer/sdu",name="Series-Trailer-SDU"]
======
======
====

[[conf_series_header_sdu]]
[conformance_test]
====
[%metadata]
name:: Series-Header-SDU
label:: /conf/series_header/sdu
description:: To confirm that an implementation of a Series Header conforms to the
Logical Model.
test-purpose:: To confirm that a Series Header is implemented in accordance with the
Logical Model.
reference:: /req/series_header/sdu
test-method:: Inspection
====

[[conf_geoposeduration_sdu]]
[conformance_test]
====
[%metadata]
name:: GP-Duration-SDU
label:: /conf/geopose_duration/sdu
description:: To confirm the correct properties of a GeoPose Duration.
test-purpose:: To confirm that a Logical Model attribute GeoPoseDuration is expressed in
seconds multiplied by 1,000 and that the unit of measure is milliseconds.
reference:: /req/geopose_duration/sdu
test-method:: Inspection
====

[conformance_test]
====
[%metadata]
name:: FS-Authority-SDU
label:: /conf/frame_specification_authority/sdu
description:: To confirm the correct properties of a Frame Specification Authority.
test-purpose:: To confirm that a FrameSpecification.authority attribute contains a string
uniquely specifying a source of reference frame specifications.
reference:: /req/frame_specification_authority/sdu
test-method:: Inspection
====

[conformance_test]
====
[%metadata]
name:: FS-ID-SDU
label:: /conf/frame_specification_id/sdu
description:: To confirm the correct properties of a Frame Specification ID.
test-purpose:: To confirm that a FrameSpecification.id attribute contains a string
uniquely specifying the identity of a reference frame specification as defined by
that authority.
reference:: /req/frame_specification_id/sdu
test-method:: Inspection
====

[conformance_test]
====
[%metadata]
name:: FS-Parameters-SDU
label:: /conf/frame_specification_parameters/sdu
description:: To confirm the correct properties of Frame Specification Parameters.
test-purpose:: To confirm that a FrameSpecification.parameters attribute contains contain
all parameters needed for the corresponding authority and ID.
reference:: /req/frame_specification_parameters/sdu
test-method:: Inspection
====

[[conf_series_trailer_sdu]]
[conformance_test]
====
[%metadata]
name:: Series-Trailer-SDU
label:: /conf/series_trailer/sdu
description:: To confirm that an implementation of a Series Trailer conforms to the
Logical Model.
test-purpose:: To confirm that a Series Trailer is implemented in accordance with the
Logical Model.
reference:: /req/series_trailer/sdu
test-method:: Inspection
====

==== Irregular Series SDU Conformance Class

[[conf_class_irregular_series_sdu]]
[conformance_class]
====
[%metadata]
name:: Irregular Series SDU
label:: /conf/class/irregular_series/sdu
subject:: <<req_irregular_series_sdu,Requirements Class "Irregular Series SDU">>
classification:: Target Type:SDU
description:: To confirm that a Regular Series conforms to the Logical Model.
inherit:: /conf/global

[conformance_test,label="/conf/series_header/sdu",name="Series-Header-SDU"]
======
======

[conformance_test,label="/conf/geopose_duration/sdu",name="GP-Duration-SDU"]
======
======

[conformance_test,label="/conf/frame_specification_authority/sdu",name="FS-Authority-SDU"]
======
======

[conformance_test,label="/conf/frame_specification_id/sdu",name="FS-ID-SDU"]
======
======

[conformance_test,label="/conf/frame_specification_parameters/sdu",name="FS-Parameters-SDU"]
======
======

[conformance_test,label="/conf/series_frame_and_time/sdu",name="Series-Frame-And-Time-SDU"]
======
======

[conformance_test,label="/conf/series_trailer/sdu",name="Series-Trailer-SDU"]
======
======
====

[conformance_test]
====
[%metadata]
name:: Series-Header-SDU
label:: /conf/series_header/sdu
description:: To confirm that an implementation of a Series Header conforms to the
Logical Model.
test-purpose:: To confirm that a Series Header is implemented in accordance with the
Logical Model.
reference:: /req/series_header/sdu
test-method:: Inspection
====

[conformance_test]
====
[%metadata]
name:: FS-Authority-SDU
label:: /conf/frame_specification_authority/sdu
description:: To confirm the correct properties of a Frame Specification Authority.
test-purpose:: To confirm that a FrameSpecification.authority attribute contains a string
uniquely specifying a source of reference frame specifications.
reference:: /req/frame_specification_authority/sdu
test-method:: Inspection
====

[conformance_test]
====
[%metadata]
name:: FS-ID-SDU
label:: /conf/frame_specification_id/sdu
description:: To confirm the correct properties of a Frame Specification ID.
test-purpose:: To confirm that a FrameSpecification.id attribute contains a string
uniquely specifying the identity of a reference frame specification as defined by
that authority.
reference:: /req/frame_specification_id/sdu
test-method:: Inspection
====

[conformance_test]
====
[%metadata]
name:: FS-Parameters-SDU
label:: /conf/frame_specification_parameters/sdu
description:: To confirm the correct properties of Frame Specification Parameters.
test-purpose:: To confirm that a FrameSpecification.parameters attribute contains contain
all parameters needed for the corresponding authority and ID.
reference:: /req/frame_specification_parameters/sdu
test-method:: Inspection
====

[conformance_test]
====
[%metadata]
name:: Series-Frame-And-Time-SDU
label:: /conf/series_frame_and_time/sdu
description:: To confirm that an implementation of a Series FrameAndTime object
conforms to the Logical Model.
test-purpose:: To confirm that a Series FrameAndTime is implemented in accordance with the
Logical Model.
reference:: /req/series_frame_and_time/sdu
test-method:: Inspection
====

[conformance_test]
====
[%metadata]
name:: Series-Trailer-SDU
label:: /conf/series_trailer/sdu
description:: To confirm that an implementation of a Series Trailer conforms to the
Logical Model.
test-purpose:: To confirm that a Series Trailer is implemented in accordance with the
Logical Model.
reference:: /req/series_trailer/sdu
test-method:: Inspection
====

==== Stream SDU Conformance Class

[[conf_class_stream_sdu]]
[conformance_class]
====
[%metadata]
name:: Stream SDU
label:: /conf/class/stream/sdu
subject:: <<req_stream_sdu,Requirements Class "Stream SDU">>
classification:: Target Type:SDU
description:: To confirm that a GeoPose Stream conforms to the Logical Model.
inherit:: /conf/global

[conformance_test,label="/conf/transition_model/sdu",name="Transition-Model-SDU"]
======
======

[conformance_test,label="/conf/frame_specification_authority/sdu",name="FS-Authority-SDU"]
======
======

[conformance_test,label="/conf/frame_specification_id/sdu",name="FS-ID-SDU"]
======
======

[conformance_test,label="/conf/frame_specification_parameters/sdu",name="FS-Parameters-SDU"]
======
======

[abstract_test,label="/conf/stream_frame_and_time/sdu",name="Stream-Frame-And-Time-SDU"]
======
======
====

[[conf_transition_model_sdu]]
[conformance_test]
====
[%metadata]
name:: Transition-Model-SDU
label:: /conf/frame_specification_authority/sdu
description:: To confirm that a TransitionModel attribute conforms to the Logical
Model.
test-purpose:: To confirm that a transition_model attribute is one of the values in the
TransitionModel enumeration.
reference:: /req/transition_model/sdu
test-method:: Inspection
====

[conformance_test]
====
[%metadata]
name:: FS-Authority-SDU
label:: /conf/frame_specification_authority/sdu
description:: To confirm the correct properties of a Frame Specification Authority.
test-purpose:: To confirm that a FrameSpecification.authority attribute contains a string
uniquely specifying a source of reference frame specifications.
reference:: /req/frame_specification_authority/sdu
test-method:: Inspection
====

[conformance_test]
====
[%metadata]
name:: FS-ID-SDU
label:: /conf/frame_specification_id/sdu
description:: To confirm the correct properties of a Frame Specification ID.
test-purpose:: To confirm that a FrameSpecification.id attribute contains a string
uniquely specifying the identity of a reference frame specification as defined by
that authority.
reference:: /req/frame_specification_id/sdu
test-method:: Inspection
====

[conformance_test]
====
[%metadata]
name:: FS-Parameters-SDU
label:: /conf/frame_specification_parameters/sdu
description:: To confirm the correct properties of Frame Specification Parameters.
test-purpose:: To confirm that a FrameSpecification.parameters attribute contains contain
all parameters needed for the corresponding authority and ID.
reference:: /req/frame_specification_parameters/sdu
test-method:: Inspection
====

[[conf_stream_frame_and_time_sdu]]
[abstract_test]
====
[%metadata]
label:: /conf/stream/frame_and_time/sdu
test-purpose:: To confirm that a Stream frame_and_time is implemented as an
innerFrameAndTime property with an ExplicitFrameSpec and GeoPoseInstant pair.
inherit:: /req/Stream/fst/sdu
test-method:: Inspection
====

=== Encodings Conformance

Each encoding technology has its own independent test suite. There is one
conformance class per Standardization target per encoding technology. The GeoPose
Standard 1.0 has one encoding technology: JSON.

==== JSON Conformance

The *Basic-YPR GeoPose* is the JSON encoding intended for widest use.

[[conf_class_basic_ypr_encoding_json]]
[conformance_class]
====
[%metadata]
name:: Basic-YPR Encoding-JSON
label:: /conf/class/basic_ypr/encoding/json
subject:: JSON object
description:: To confirm that a Basic-YPR GeoPose consists of an Outer Frame
specified by an implicit WGS-84 CRS and an implicit EPSG 4461-CS (LTP-ENU) coordinate
system and explicit parameters defining the tangent point and that the Inner Frame is
a rotation-only transformation using Yaw, Pitch, and Roll angles.
inherit:: /conf/basic_ypr_sdu

[conformance_test,label="/conf/basic_ypr/encoding/json/test",name="B-YPR-Encoding-JSON"]
======
======
====

The Basic-YPR JSON Encoding member test is the following:

[[conf_basic_ypr_encoding_json_test]]
[conformance_test]
====
[%metadata]
name:: B-YPR-Encoding-JSON
label:: /conf/basic_ypr/encoding/json/test
description:: To confirm that a JSON encoding of a Basic-YPR GeoPose conforms with
the corresponding JSON-Schema definition.
test-purpose:: To confirm that Basic-YPR GeoPose data objects conform to the Basic-YPR
JSON-Schema definition.
test-method:: JSON-Schema validation.
reference:: /req/basic_ypr/sdu
classification:: Test Type:Conformance
====

The *Basic-Quaternion GeoPose* JSON encoding is intended for applications using
quaternions. It comes in two sub-versions: normal and strict. The only difference is
that a strict sub-version does not allow additional JSON members.

[[conf_basic_quaternion_encoding_json]]
[conformance_class]
====
[%metadata]
name:: Basic-Quaternion Encoding-JSON
label:: /conf/class/basic_quaternion/encoding/json
subject:: JSON object
description:: Confirm that a JSON-encoded Basic-Quaternion GeoPose conforms to the
relevant elements of the Logical Model and a corresponding JSON-Schema document.
inherit:: /conf/basic_ypr_sdu

[conformance_test,label="/conf/basic_ypr/encoding/json/test"]
======
======
====

The *Basic-Quaternion* JSON Encoding member test is the following:

[[conf_basic_quaternion_encoding_json_test]]
[conformance_test]
====
[%metadata]
name:: B-Quaternion-Encoding-JSON
label:: /conf/basic_ypr/encoding/json/test
description:: Confirm that Basic-Quaternion GeoPose data objects conform to the
Basic-Quaternion JSON-Schema definition.
test-purpose:: To confirm that Basic-Quaternion GeoPose data objects conform to the
Basic-Quaternion JSON-Schema definition.
test-method:: JSON-Schema validation.
reference:: /req/basic_quaternion/sdu
classification:: Test Type:Conformance
====

[NOTE]
The *Basic-Quaternion (Strict) GeoPose* JSON encoding does not allow additional JSON
members.

[[conf_class_basic_quaternion_encoding_json]]
[conformance_class]
====
[%metadata]
name:: Basic-Quaternion Encoding-JSON (Strict)
label:: /conf/class/quaternion/encoding/json_strict
subject:: JSON object
description:: Confirm that a strict JSON-encoded Basic-Quaternion GeoPose conforms to
the relevant elements of the Logical Model and a corresponding JSON-Schema document.
inherit:: /conf/basic_quaternion_sdu

[conformance_test,label="/conf/basic_quaternion/encoding/json_strict",name="B-Quaternion-Encoding-JSON-Strict"]
======
======
====

The Basic-Quaternion JSON (Strict) Encoding member test is the following:

[[conf_basic_quaternion_encoding_json_strict_test]]
[conformance_test]
====
[%metadata]
name:: B-Quaternion-Encoding-JSON (Strict)
label:: /conf/basic_quaternion/encoding/json_strict
description:: Confirm that Basic-Quaternion (Strict) GeoPose data objects conform to
the Basic-Quaternion (Strict) JSON-Schema definition.
test-purpose:: To confirm that Basic-Quaternion (Strict) GeoPose data objects conform to
the Basic-Quaternion (Strict) JSON-Schema definition.
test-method:: JSON-Schema validation.
reference:: /req/basic_quaternion/sdu
classification:: Test Type:Conformance
====

The *Advanced GeoPose* JSON encoding has an optional time stamp and a flexible Outer
Frame specification.

[[conf_class_advanced_encoding_json]]
[conformance_class]
====
[%metadata]
name:: Advanced Encoding-JSON
label:: /conf/class/advanced/encoding/json
subject:: JSON object
description:: To confirm that a JSON-encoded Advanced GeoPose conforms to the
relevant elements of the Logical Model and a specific JSON-Schema document.
inherit:: /conf/advanced_sdu

[conformance_test,label="/conf/advanced/encoding/json/test",name="Advanced-Encoding-JSON"]
======
======
====

The *Advanced GeoPose* JSON Encoding member test is the following:

[[conf_advanced_encoding_json_test]]
[conformance_test]
====
[%metadata]
name:: Advanced-Encoding-JSON
label:: /conf/advanced/encoding/json/test
description:: Confirm that a JSON-encoded Advanced GeoPose conforms to the
corresponding JSON-Schema document.
test-purpose:: To confirm that Advanced GeoPose data objects conform to the Advanced
JSON-Schema definition.
test-method:: JSON-Schema validation.
reference:: /req/advanced/sdu
classification:: Test Type:Conformance
====

The *GeoPose Chain* JSON encoding supports a linear sequence of frame transformations
for modelling articulated structures.

[[conf_class_chain_encoding_json]]
[conformance_class]
====
[%metadata]
name:: Chain Encoding-JSON
label:: /conf/class/chain/encoding/json
subject:: JSON object
description:: To confirm that a JSON-encoded GeoPose Chain conforms to the relevant
elements of the Logical Model and a specific JSON-Schema document.
inherit:: /conf/chain/sdu

[conformance_test,label="/conf/chain/encoding/json/test",name="Chain-Encoding-JSON"]
======
======
====

The Chain Encoding member test is the following:

[[conf_chain_encoding_json_test]]
[conformance_test]
====
[%metadata]
name:: Chain-Encoding-JSON
label:: /conf/chain/encoding/json
description:: Confirm that a JSON-encoded GeoPose Chain conforms to the specified
JSON-Schema document.
test-purpose:: To confirm that Chain GeoPose data objects conform to the Chain JSON-Schema
definition.
test-method:: JSON-Schema validation.
reference:: /req/chain/sdu
classification:: Test Type:Conformance
====

The *GeoPose Graph* JSON encoding supports a directed graph stucture.

[[conf_class_graph_encoding_json]]
[conformance_class]
====
[%metadata]
name:: Graph Encoding-JSON
label:: /conf/class/graph/encoding/json
subject:: JSON object
description:: To confirm that a JSON-encoded GeoPose Graph conforms to the relevant
elements of the Logical Model and a specific JSON-Schema document.
inherit:: /conf/graph/sdu

[conformance_test,label="/conf/graph/encoding/json/test",name="Graph-Encoding-JSON"]
======
======
====

The Graph Encoding member test is the following:

[[conf_graph_encoding_json_test]]
[conformance_test]
====
[%metadata]
name:: Graph-Encoding-JSON
label:: /conf/graph/encoding/json/test
description:: Confirm that GeoPose Graph data objects conform to the Graph
JSON-Schema definition.
test-purpose:: To confirm that Graph GeoPose data objects conform to the Graph JSON-Schema
definition.
test-method:: JSON-Schema validation.
reference:: /req/graph/sdu
classification:: Test Type:Conformance
====

The *GeoPose Regular Series* JSON encoding supports a time series of equally-spaced
GeoPoses.

[[conf_class_regular_series_encoding_json]]
[conformance_class]
====
[%metadata]
name:: GeoPose Regular Series Encoding-JSON
label:: /conf/class/regular_series/encoding/json
subject:: JSON object
description:: To confirm that a JSON-encoded Regular Series conforms to the relevant
elements of the Logical Model and a specific JSON-Schema document.
inherit:: /conf/regular_series/sdu

[conformance_test,label="/conf/regular_series/encoding/json",name="Regular-Series-Encoding-JSON"]
======
======
====

The *GeoPose Regular Series* JSON Encoding member test is the following:

[[conf_regular_series_encoding_json]]
[conformance_test]
====
[%metadata]
name:: GeoPose Regular Series-Encoding-JSON
label:: /conf/regular_series/encoding/json
description:: Confirm that GeoPose Regular Series data objects conform to the Regular
Series JSON-Schema definition.
test-purpose:: To confirm that Regular Series GeoPose data objects conform to the Regular
Series JSON-Schema definition.
test-method:: JSON-Schema validation.
reference:: /req/regular_series/sdu
classification:: Test Type:Conformance
====

The *GeoPose Irregular Series* JSON encoding has an optional time stamp and a
flexible Outer Frame specification.

[[conf_class_irregular_series_encoding_json]]
[conformance_class]
====
[%metadata]
name:: Irregular Series Encoding-JSON
label:: /conf/class/irregular_series/encoding/json
subject:: JSON object
description:: To confirm that a JSON-encoded Irregular Series conforms to the
relevant elements of the Logical Model and a specific JSON-Schema document.
inherit:: /conf/irregular_series/sdu

[conformance_test,label="/conf/irregular_series/encoding/json/test",name="Chain"]
======
======
====

The *GeoPose Irregular Series* JSON Encoding member test is the following:

[[conf_irregular_series_encoding_json_test]]
[conformance_test]
====
[%metadata]
name:: Series-Irregular-Encoding-JSON
label:: /conf/irregular_series/encoding/json/test
description:: Confirm that GeoPose Irregular Series data objects conform to the
Regular Series JSON-Schema definition.
test-purpose:: To confirm that GeoPose Irregular Series data objects conform to the
Regular Series JSON-Schema definition.
test-method:: JSON-Schema validation.
reference:: /req/irregular_series/sdu
classification:: Test Type:Conformance
====

The *GeoPose Stream* JSON encoding has an optional time stamp and a flexible Outer
Frame specification.

[[conf_class_stream_encoding_json]]
[conformance_class]
====
[%metadata]
name:: Stream Encoding-JSON
label:: /conf/class/stream/encoding/json
subject:: JSON object
description:: Confirm that GeoPose Stream data objects conform to the corresponding
Stream JSON-Schema requirement.
inherit:: /conf/stream/sdu

[conformance_test,label="/conf/stream/encoding/json/test",name="Stream-Encoding-JSON"]
======
======
====

The *GeoPose Stream* JSON Encoding member test is the following:

[[conf_stream_encoding_json_test]]
[conformance_test]
====
[%metadata]
name:: Stream-Encoding-JSON
label:: /conf/stream/encoding/json/test
description:: Confirm that GeoPose Stream data objects conform to the Stream
JSON-Schema requirement.
test-purpose:: To confirm that Stream data objects conform to the corresponding Stream
JSON-Schema definition.
test-method:: JSON-Schema validation.
reference:: /req/stream/sdu
classification:: Test Type:Conformance
====
