== Conformance



Conformance with this standard shall be checked using all the relevant tests specified in Annex A (Normative) of this document. The framework, concepts, and methodology for testing, and the criteria to be achieved to claim conformance are specified in the OGC Compliance Testing Policies and Procedures and the OGC Compliance Testing web site. GeoPose 1.0 JSON encodings are specified via JSON-Schema:2019-9 and most of the requirements are that conforming encoded data objects shall validate against the corresponding schema.

In order to conform to this OGC® interface standard, a software implementation shall choose to implement any one of the eight Standardization Targets specified in Annex A (normative).

All requirements-classes and conformance-classes described in this document are owned by the standard(s) identified.

=== Modularity

This standard describes eight Standarization Targets. These targets are independent and a conforming implementation may implement one or more of them.

=== Conformance Classes

This standard identifies eight conformance classes. One conformance class is defined for each correspoding set of Structural Data Units, each linked to the Logical Model. Additionally, each of the eight standarization targets is represented by a conformance class, defined by a requirements class.
The tests in <<abstract-test-suite,Annex A>> are organized by Requirements Class. An implementation of a conformance class must pass all tests specified in Annex A for the corresponding requirements class.

No conformance class has a dependency on another conformance class.

The Logical Model is the root normative part of this standard.

