== Terms and Definitions

[[geopose_conceptual_model]]
[.boilerplate]
=== {blank}

The GeoPose Conceptual Model(CM) consists of linked definitions of terms denoting concepts expressed in the GeoPose LM and structural data unit(SDU) specifications for the standardization targets. The CM describes a (non-normative) domain of discourse for terms used in defining a precise and normative Logical Model(LM) expressed as a Unified Modelling Language (UML) class diagram.

The scope of the standardization targets is a subset of the scope of the LM. The scope of the LM is a subset of the scope of the Conceptual Model. The standardization targets are mutually independent implementations of subsets of the LM.

"Conceptual model: a description of common concepts and their relationships, particularly in order to facilitate exchange of information between parties within a specific domain [CEN ENV 1613:1994]. A conceptual model is explicitly chosen to be may be informed by, but independent of design or implementation concerns."

***

*Conventions*
 
***

Defined terms are in bold caps. Underlined and bolded terms are linked to the defined term. 

***

=== Spatial Concepts
 
==== position
alt:[OGC direct position]

set of coordinates of a point in a 3D Euclidean space and associated {{reference frame,options="noref"}}

==== orientation

rotational relationship between two {{reference frame,reference frames,options="noref"}}

==== pose

representation of a {{frame transform,options="noref"}} mapping the space of an {{outer frame,outer (reference) frame,options="noref"}} to the space of an {{inner frame,inner (reference) frame,options="noref"}}. A {{pose,options="noref"}} may be associated with additional non-geometrical properties such as time of observation or validity. {{pose,Poses,options="noref"}} in computer graphics often have an {{outer frame,options="noref"}} defined by a parent node in a scene graph and an {{inner frame,options="noref"}} define by a {{position,options="noref"}} and an orientation.

==== GeoPose

{{pose,options="noref"}} whose associated {{outer frame,options="noref"}} or a {{pose chain,options="noref"}} whose associated {{outermost frame,options="noref"}} is a {{topocentric (reference) frame,topocentric frame,options="noref"}} defined by an {{extrinsic frame specification,extrinsic specification,options="noref"}} related to the {{ephemeris object,options="noref"}} planet Earth.

==== reference frame

system of location and measurement often defined by a {{frame specification,options="noref"}} usually including a coordinate system to be used within a corresponding space

==== frame transform

consists of a pair of {{reference frame,reference frames,options="noref"}} and a bi-continuous coordinate transformation relating points in the corresponding spaces. The two {{reference frame,frames,options="noref"}} are called {{outer frame,options="noref"}} (domain) and {{inner frame,options="noref"}} (range).  Only an {{outer frame,options="noref"}} may have an {{extrinsic frame specification,extrinsic specification,options="noref"}}. [A {{frame transform,options="noref"}} functions as a directed edge in a {{frame graph,options="noref"}} representation of the transformational relationship between {{reference frame,frames,options="noref"}}.]

==== outer frame

first of two {{reference frame,reference frames,options="noref"}} associated with a {{frame transform,options="noref"}}

[NOTE]
In the NASA SPICE system, the {{outer frame,options="noref"}} is referred to as the *from* {{reference frame,frame,options="noref"}}. In the ROS SDF documentation, the {{outer frame,options="noref"}} is referred to as the *Parent* {{reference frame,frame,options="noref"}}. In ISO 19162, the {{outer frame,options="noref"}} is referred to as the *base* {{reference frame,frame,options="noref"}}.

==== inner frame

second of two {{reference frame,reference frames,options="noref"}} associated with a {{frame transform,options="noref"}}. An {{inner frame,options="noref"}} may not be a {{topocentric (reference) frame, topocentric frame,options="noref"}}.

[NOTE]
In the NASA SPICE system, the {{inner frame,options="noref"}} is referred to as the *to* {{reference frame,frame,options="noref"}}. In the ROS SDF documentation, the {{inner frame,options="noref"}} is referred to as the *child* {{reference frame,frame,options="noref"}}. In ISO 19162, the {{inner frame,options="noref"}} is referred to as the *derived* {{reference frame,frame,options="noref"}}.

==== outermost frame

{{outer frame,options="noref"}} of the first {{frame transform,options="noref"}} in a {{pose chain,options="noref"}}

==== innermost frame

{{inner frame,options="noref"}} of the last {{frame transform,options="noref"}} in a {{pose chain,options="noref"}}

==== ephemeris object

physical object or manifestation of a physical object that can be characterized by an externally-defined (possibly time-dependent) location and orientation in a 3-dimensional space

==== topocentric (reference) frame

{{reference frame,frame,options="noref"}} that has an {{extrinsic frame specification,extrinsic specification,options="noref"}} associated with a location on or near the surface of a natural body, such as planet Earth. [This is the definition used in the NASA SPICE system.] In connection with a GeoPose, one way that a {{topocentric (reference) frame,topocentric frame,options="noref"}} may be realized is by a {{local tangent plane coordinate system,local tangent plane east-north-up frame (LTP-ENU),options="noref"}} attached to the surface of a body, to a gravitational equipotential surface ({{geoid,options="noref"}} in the case of planet Earth), or to a mathematical surface such as an {{ellipsoid,options="noref"}} approximating a {{geoid,options="noref"}}.

==== frame specification

data that completely and uniquely defines a {{reference frame,options="noref"}}. In the context of Poses, there are {{extrinsic frame specification,extrinsic specifications,options="noref"}} defined by an external data source, and {{derived frame specification,derived specifications,options="noref"}} defined by a transformation from another {{reference frame,options="noref"}}.

==== extrinsic frame specification

relates a {{reference frame,options="noref"}} to an {{ephemeris object,options="noref"}} or other external reference, which may be based on joint properties of a group of objects, such as the center of mass of the Earth-Moon system

==== derived frame specification

relates a {{reference frame,options="noref"}} to another {{reference frame,frame,options="noref"}} by a {{frame transform,options="noref"}} or its inverse

==== frame graph

directed acyclic graph representation of the transformational relationships between {{reference frame,reference frames,options="noref"}}. {{reference frame,frames,options="noref"}} are the nodes or vertices of the graph. {{frame transform,frame transforms,options="noref"}} are the edges of the graph, directed from the {{outer frame,options="noref"}} to the {{inner frame,options="noref"}}. Note that there may be zero, one, or many paths between two distinct vertices, i.e. {{reference frame,frames,options="noref"}}. Multiple paths correspond to real-world situations with, for example, redundant line-of-sight links in point-to-point radio networks used in communication systems.]

==== pose chain

directed path in a {{frame graph,options="noref"}} connecting an {{outermost frame,options="noref"}} to an {{innermost frame,options="noref"}}. The sequence of {{frame transform,frame transforms,options="noref"}} in a {{pose chain,options="noref"}} may be combined in a single composite transformation. [There may exist multiple {{pose chain,pose chains,options="noref"}} linking the same {{outermost frame,options="noref"}} and {{innermost frame,options="noref"}} and the corresponding composite transformations may not agree. This is intentional, representing real-world configurations and capabilities of sensors and communication links.]

=== Sequence and Stream Concepts

==== sequence
alt:[GeoPose sequence]

set of {{pose,(member) poses,options="noref"}} ordered by {{valid time,options="noref"}} and pertaining to the same underlying physical object or construct. Each successive {{pose,(member) pose,options="noref"}} must have a {{valid time,options="noref"}} after its predecessor.

==== inter-pose duration

time {{duration,options="noref"}} between consecutive {{pose,poses,options="noref"}} in a {{sequence,options="noref"}}

==== closed sequence
alt:[closed pose sequence]

{{sequence,GeoPose sequence,options="noref"}} of fixed length with specific meta-data that fully characterize the sequence and its {{members}}

==== regular sequence
alt:[regular GeoPose sequence]

{{closed sequence,options="noref"}} with a constant {{inter-pose duration,options="noref"}}

==== irregular sequence
alt:[irregular GeoPose sequence]

{{closed sequence,options="noref"}} with a variable {{inter-pose duration,options="noref"}}. Each {{pose,options="noref"}} in an {{irregular sequence,options="noref"}} has an associated {{valid time,options="noref"}}.

==== GeoPose stream

{{irregular sequence,options="noref"}} of unbounded length

==== header
alt:[sequence header]

metadata essential for interpretation of the following {{members}} of a {{sequence,options="noref"}}

==== transition model

metadata that indicates whether or how it may be possible to estimate {{pose,poses,options="noref"}} in the interval between consecutive {{pose,poses,options="noref"}} in a {{sequence,options="noref"}}

==== trailer
alt:[sequence trailer]

metadata essential for validation of the preceding {{members}} of a {{sequence,options="noref"}}. 

=== Temporal Concepts

These terms are intended to align with terms used in OWL-TIME (https://www.w3.org/TR/owl-time/) . The only temporal frame used in this GeoPose standard is "Unix Time": seconds since the Unix Epoch of 1 January 1970 measured by a virtual "Unix clock", ticking once per "Unix second", and omitting any corrections such as leap seconds. Times before 1 January 1972 are not precisely related to another temporal frame but the value at UTC 1 January 1972 was +63,072,000. This allows precise conversion to and from modern temporal frames. Note that the GeoPose standard does not reference a calendar and encoded values are representations of the count of seconds, rather than a calendar-relative date and time. These times may be converted to UTC and expressed as text (e.g. with ISO 8601-1:2019 and ISO 8601-2:2019) relative to a specific calendar but this is outside the GeoPose scope.

==== temporal frame

specification for the interpretation of points on a {{time line,options="noref"}} as {{instant,instants,options="noref"}} in relation to a specified {{epoch,options="noref"}}

==== time line
alt:[time axis]

one-dimensional {{euclidean space}} whose points represent an ordered sequence of {{instant,instants,options="noref"}} directed from the past to the future

==== instant

specific point on a {{time line,options="noref"}}

==== interval

the timespan between two {{instant,instants,options="noref"}} on a {{time line,options="noref"}}, interpreted in context of the associated {{temporal frame,options="noref"}}

==== duration

semi-open: It includes the earlier {{instant,options="noref"}} but not the later {{instant,options="noref"}}

==== duration

of an {{interval,options="noref"}} is the one-dimensional signed distance between its bounding {{instant,instants,options="noref"}}. The magnitude of a {{length}} value depends on the {{temporal frame,options="noref"}}.

==== epoch

specified {{instant,options="noref"}} that can be used as a reference point to calculate {{temporal relationship,temporal relationships,options="noref"}} and {{duration,durations,options="noref"}} between {{instant,instants,options="noref"}}.

==== temporal relationship

between two {{instant,instants,options="noref"}} is one of: *before*, *coincident*, or *after*. {{temporal relationship,temporal relationships,options="noref"}} are only valid within the context of a specific {{temporal frame,options="noref"}}.

=== Temporal Database Concepts

==== valid time

{{time line,options="noref"}} where the time of changes in the existence or validity of real-world objects or property values are located. {{instant,instants,options="noref"}} in {{valid time,options="noref"}} mark the temporal location of real-world transitions in existence, property values, or their validity.

==== transaction time

{{time line,options="noref"}} where the time of changes in the presence or validity of the representations of real-world objects or their properties in an information system are located. {{instant,instants,options="noref"}} in {{transaction time,options="noref"}} mark the temporal location of actions that create, update, or delete representations of objects or properties.

[NOTE]
====
Both of the terms {{valid time,options="noref"}}> and {{transaction time,options="noref"}} are used in ways that can refer to {{instant,instants,options="noref"}} or to {{time line,time lines,options="noref"}}.
====

==== bi-temporality

property of a data representation that denotes that it carries both {{valid time,valid,options="noref"}} and {{transaction time,transaction times,options="noref"}}
