== Terms and definitions

[[geopose_conceptual_model]]
[.boilerplate]
=== {blank}

The GeoPose Conceptual Model(CM) consists of linked definitions of terms denoting concepts expressed in the GeoPose LM and structural data unit(SDU) specifications for the standardization targets. The CM describes a (non-normative) domain of discourse for terms used in defining a precise and normative Logical Model(LM) expressed as a Unified Modelling Language (UML) class diagram.

The scope of the standardization targets is a subset of the scope of the LM. The scope of the LM is a subset of the scope of the Conceptual Model. The standardization targets are mutually independent implementations of subsets of the LM.

"Conceptual model: a description of common concepts and their relationships, particularly in order to facilitate exchange of information between parties within a specific domain [CEN ENV 1613:1994]. A conceptual model is explicitly chosen to be may be informed by, but independent of design or implementation concerns."


=== Spatial Concepts
 
==== position
alt:[OGC direct position]

set of coordinates of a point in a 3D Euclidean space and associated {{reference frame}}

==== orientation

rotational relationship between two {{reference frame,reference frames}}

==== pose

representation of a {{frame transform}} mapping the space of an {{outer frame,outer (reference) frame}} to the space of an {{inner frame,inner (reference) frame}}. A {{pose}} may be associated with additional non-geometrical properties such as time of observation or validity. {{pose,Poses}} in computer graphics often have an {{outer frame}} defined by a parent node in a scene graph and an {{inner frame}} define by a {{position}} and an orientation.

==== GeoPose

{{pose}} whose associated {{outer frame}} or a {{pose chain}} whose associated {{outermost frame}} is a {{topocentric (reference) frame,topocentric frame}} defined by an {{extrinsic frame specification,extrinsic specification}} related to the {{ephemeris object}} planet Earth.

==== reference frame

system of location and measurement often defined by a {{frame specification}} usually including a coordinate system to be used within a corresponding space

==== frame transform

consists of a pair of {{reference frame,reference frames}} and a bi-continuous coordinate transformation relating points in the corresponding spaces. The two {{reference frame,frames}} are called {{outer frame}} (domain) and {{inner frame}} (range).  Only an {{outer frame}} may have an {{extrinsic frame specification,extrinsic specification}}. [A {{frame transform}} functions as a directed edge in a {{frame graph}} representation of the transformational relationship between {{reference frame,frames}}.]

==== outer frame

first of two {{reference frame,reference frames}} associated with a {{frame transform}}

[NOTE]
In the NASA SPICE system, the {{outer frame}} is referred to as the *from* {{reference frame,frame}}. In the ROS SDF documentation, the {{outer frame}} is referred to as the *Parent* {{reference frame,frame}}. In ISO 19162, the {{outer frame}} is referred to as the *base* {{reference frame,frame}}.

==== inner frame

second of two {{reference frame,reference frames}} associated with a {{frame transform}}. An {{inner frame}} may not be a {{topocentric (reference) frame, topocentric frame}}.

[NOTE]
In the NASA SPICE system, the {{inner frame}} is referred to as the *to* {{reference frame,frame}}. In the ROS SDF documentation, the {{inner frame}} is referred to as the *child* {{reference frame,frame}}. In ISO 19162, the {{inner frame}} is referred to as the *derived* {{reference frame,frame}}.

==== outermost frame

{{outer frame}} of the first {{frame transform}} in a {{pose chain}}

==== innermost frame

{{inner frame}} of the last {{frame transform}} in a {{pose chain}}

==== ephemeris object

physical object or manifestation of a physical object that can be characterized by an externally-defined (possibly time-dependent) location and orientation in a 3-dimensional space

==== topocentric (reference) frame

{{reference frame,frame}} that has an {{extrinsic frame specification,extrinsic specification}} associated with a location on or near the surface of a natural body, such as planet Earth. [This is the definition used in the NASA SPICE system.] In connection with a GeoPose, one way that a {{topocentric (reference) frame,topocentric frame}} may be realized is by a {{local tangent plane coordinate system,local tangent plane east-north-up frame (LTP-ENU)}} attached to the surface of a body, to a gravitational equipotential surface ({{geoid}} in the case of planet Earth), or to a mathematical surface such as an {{ellipsoid}} approximating a {{geoid}}.

==== frame specification

data that completely and uniquely defines a {{reference frame}}. In the context of Poses, there are {{extrinsic frame specification,extrinsic specifications}} defined by an external data source, and {{derived frame specification,derived specifications}} defined by a transformation from another {{reference frame}}.

==== extrinsic frame specification

relates a {{reference frame}} to an {{ephemeris object}} or other external reference, which may be based on joint properties of a group of objects, such as the center of mass of the Earth-Moon system

==== derived frame specification

relates a {{reference frame}} to another {{reference frame,frame}} by a {{frame transform}} or its inverse

==== frame graph

directed acyclic graph representation of the transformational relationships between {{reference frame,reference frames}}. {{reference frame,frames}} are the nodes or vertices of the graph. {{frame transform,frame transforms}} are the edges of the graph, directed from the {{outer frame}} to the {{inner frame}}. Note that there may be zero, one, or many paths between two distinct vertices, i.e. {{reference frame,frames}}. Multiple paths correspond to real-world situations with, for example, redundant line-of-sight links in point-to-point radio networks used in communication systems.]

==== pose chain

directed path in a {{frame graph}} connecting an {{outermost frame}} to an {{innermost frame}}. The sequence of {{frame transform,frame transforms}} in a {{pose chain}} may be combined in a single composite transformation. [There may exist multiple {{pose chain,pose chains}} linking the same {{outermost frame}} and {{innermost frame}} and the corresponding composite transformations may not agree. This is intentional, representing real-world configurations and capabilities of sensors and communication links.]

=== Sequence and Stream Concepts

==== sequence
alt:[GeoPose sequence]

set of {{pose,(member) poses}} ordered by {{valid time}} and pertaining to the same underlying physical object or construct. Each successive {{pose,(member) pose}} must have a {{valid time}} after its predecessor.

==== inter-pose duration

time {{duration}} between consecutive {{pose,poses}} in a {{sequence}}

==== closed sequence
alt:[closed pose sequence]

{{sequence,GeoPose sequence}} of fixed length with specific meta-data that fully characterize the sequence and its {{members}}

==== regular sequence
alt:[regular GeoPose sequence]

{{closed sequence}} with a constant {{inter-pose duration}}

==== irregular sequence
alt:[irregular GeoPose sequence]

{{closed sequence}} with a variable {{inter-pose duration}}. Each {{pose}} in an {{irregular sequence}} has an associated {{valid time}}.

==== GeoPose stream

{{irregular sequence}} of unbounded length

==== header
alt:[sequence header]

metadata essential for interpretation of the following {{members}} of a {{sequence}}

==== transition model

metadata that indicates whether or how it may be possible to estimate {{pose,poses}} in the interval between consecutive {{pose,poses}} in a {{sequence}}

==== trailer
alt:[sequence trailer]

metadata essential for validation of the preceding {{members}} of a {{sequence}}. 

=== Temporal Concepts

These terms are intended to align with terms used in OWL-TIME (https://www.w3.org/TR/owl-time/) . The only temporal frame used in this GeoPose standard is "Unix Time": seconds since the Unix Epoch of 1 January 1970 measured by a virtual "Unix clock", ticking once per "Unix second", and omitting any corrections such as leap seconds. Times before 1 January 1972 are not precisely related to another temporal frame but the value at UTC 1 January 1972 was +63,072,000. This allows precise conversion to and from modern temporal frames. Note that the GeoPose standard does not reference a calendar and encoded values are representations of the count of seconds, rather than a calendar-relative date and time. These times may be converted to UTC and expressed as text (e.g. with ISO 8601-1:2019 and ISO 8601-2:2019) relative to a specific calendar but this is outside the GeoPose scope.

==== temporal frame

specification for the interpretation of points on a {{time line}} as {{instant,instants}} in relation to a specified {{epoch}}

==== time line
alt:[time axis]

one-dimensional {{euclidean space}} whose points represent an ordered sequence of {{instant,instants}} directed from the past to the future

==== instant

specific point on a {{time line}}

==== interval

the timespan between two {{instant,instants}} on a {{time line}}, interpreted in context of the associated {{temporal frame}}

==== duration

semi-open: It includes the earlier {{instant}} but not the later {{instant}}

==== duration

of an {{interval}} is the one-dimensional signed distance between its bounding {{instant,instants}}. The magnitude of a {{length}} value depends on the {{temporal frame}}.

==== epoch

specified {{instant}} that can be used as a reference point to calculate {{temporal relationship,temporal relationships}} and {{duration,durations}} between {{instant,instants}}.

==== temporal relationship

between two {{instant,instants}} is one of: *before*, *coincident*, or *after*. {{temporal relationship,temporal relationships}} are only valid within the context of a specific {{temporal frame}}.

=== Temporal Database Concepts

==== valid time

{{time line}} where the time of changes in the existence or validity of real-world objects or property values are located. {{instant,instants}} in {{valid time}} mark the temporal location of real-world transitions in existence, property values, or their validity.

==== transaction time

{{time line}} where the time of changes in the presence or validity of the representations of real-world objects or their properties in an information system are located. {{instant,instants}} in {{transaction time}} mark the temporal location of actions that create, update, or delete representations of objects or properties.

[NOTE]
====
Both of the terms {{valid time}}> and {{transaction time}} are used in ways that can refer to {{instant,instants}} or to {{time line,time lines}}.
====

==== bi-temporality

property of a data representation that denotes that it carries both {{valid time,valid}} and {{transaction time,transaction times}}
