name: generate

on:
  push:
    branches: [ master, main ]
  pull_request:
  workflow_dispatch:

jobs:
  test-linux:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v2
        with:
          path: ~/.fontist
          key: fontist-${{ runner.os }}
          restore-keys: fontist-${{ runner.os }}

      - uses: actions-mn/setup@main

      - run: metanorma site generate --agree-to-terms
